In [2]:
import pandas as pd 
import os

print(os.getcwd())
print(os.listdir())

C:\Users\Laharika\OneDrive\Desktop\MedTrack_DV\Data Set
['.ipynb_checkpoints', '01_Data_Collection_and_Integration.ipynb', 'admission.csv', 'bed.csv', 'billing.csv', 'billing_detail.csv', 'department.csv', 'diagnostic_test.csv', 'Dim_Department.csv', 'Dim_Disease.csv', 'Dim_Doctor.csv', 'Dim_Drug.csv', 'Dim_Insurance.csv', 'Dim_Patient.csv', 'Dim_Ward.csv', 'disease.csv', 'doctor.csv', 'drug.csv', 'drug_inventory.csv', 'drug_manufacturer.csv', 'employee.csv', 'Fact_Admissions.csv', 'insurance_provider.csv', 'KPI Engineering.ipynb', 'patient.csv', 'patient_diagnostic.csv', 'patient_insurance.csv', 'prescription.csv', 'staff_assignment.csv', 'ward.csv']

In [3]:
admission = pd.read_csv("admission.csv")
bed = pd.read_csv("bed.csv")
billing = pd.read_csv("billing.csv")
billing_detail = pd.read_csv("billing_detail.csv")
department = pd.read_csv("department.csv")
diagnostic_test = pd.read_csv("diagnostic_test.csv")
disease = pd.read_csv("disease.csv")
doctor = pd.read_csv("doctor.csv")
drug = pd.read_csv("drug.csv")
drug_inventory = pd.read_csv("drug_inventory.csv")
drug_manufacturer = pd.read_csv("drug_manufacturer.csv")
employee = pd.read_csv("employee.csv")
insurance_provider = pd.read_csv("insurance_provider.csv")
patient = pd.read_csv("patient.csv")
patient_diagnostic = pd.read_csv("patient_diagnostic.csv")
patient_insurance = pd.read_csv("patient_insurance.csv")
prescription = pd.read_csv("prescription.csv")
staff_assignment = pd.read_csv("staff_assignment.csv")
ward = pd.read_csv("ward.csv")

print(" All datasets loaded successfully!")

 All datasets loaded successfully!

In [4]:
datasets = {
    "admission": admission,
    "bed": bed,
    "billing": billing,
    "billing_detail": billing_detail,
    "department": department,
    "diagnostic_test": diagnostic_test,
    "disease": disease,
    "doctor": doctor,
    "drug": drug,
    "drug_inventory": drug_inventory,
    "drug_manufacturer": drug_manufacturer,
    "employee": employee,
    "insurance_provider": insurance_provider,
    "patient": patient,
    "patient_diagnostic": patient_diagnostic,
    "patient_insurance": patient_insurance,
    "prescription": prescription,
    "staff_assignment": staff_assignment,
    "ward": ward
}

for name, df in datasets.items():
    print("=" * 60)
    print(name)
    print("Shape:", df.shape)

============================================================
admission
Shape: (45000, 10)
============================================================
bed
Shape: (415, 4)
============================================================
billing
Shape: (45000, 8)
============================================================
billing_detail
Shape: (112402, 5)
============================================================
department
Shape: (11, 5)
============================================================
diagnostic_test
Shape: (9, 5)
============================================================
disease
Shape: (20, 3)
============================================================
doctor
Shape: (98, 5)
============================================================
drug
Shape: (250, 6)
============================================================
drug_inventory
Shape: (250, 6)
============================================================
drug_manufacturer
Shape: (300, 5)
============================================================
employee
Shape: (500, 7)
============================================================
insurance_provider
Shape: (50, 5)
============================================================
patient
Shape: (30000, 6)
============================================================
patient_diagnostic
Shape: (63269, 6)
============================================================
patient_insurance
Shape: (21617, 7)
============================================================
prescription
Shape: (73109, 6)
============================================================
staff_assignment
Shape: (207, 4)
============================================================
ward
Shape: (27, 5)

In [5]:
admission.head()

,admission_id,admission_date,discharge_date,admission_type,admission_status,patient_id,department_id,ward_id,bed_id,disease_id
0,1,2020-02-25,2020-02-27,Emergency,Discharged,166,2,6,76,10
1,2,2022-02-22,2022-03-04,Elective,Discharged,8622,5,21,302,11
2,3,2021-02-03,2021-02-09,Elective,Discharged,23976,1,2,11,9
3,4,2021-12-31,2022-01-05,Elective,Discharged,16635,2,10,128,1
4,5,2022-07-02,2022-07-07,Elective,Discharged,10654,3,11,157,7

In [6]:
for name, df in datasets.items():
    print("=" * 60)
    print(name)
    display(df.head())

============================================================
admission

,admission_id,admission_date,discharge_date,admission_type,admission_status,patient_id,department_id,ward_id,bed_id,disease_id
0,1,2020-02-25,2020-02-27,Emergency,Discharged,166,2,6,76,10
1,2,2022-02-22,2022-03-04,Elective,Discharged,8622,5,21,302,11
2,3,2021-02-03,2021-02-09,Elective,Discharged,23976,1,2,11,9
3,4,2021-12-31,2022-01-05,Elective,Discharged,16635,2,10,128,1
4,5,2022-07-02,2022-07-07,Elective,Discharged,10654,3,11,157,7

============================================================
bed

   bed_id bed_number bed_status  ward_id
0       1        1-1   Occupied        1
1       2        1-2   Occupied        1
2       3        1-3  Available        1
3       4        1-4   Occupied        1
4       5        1-5   Occupied        1

============================================================
billing

,bill_id,bill_date,total_amount,insurance_covered_amount,patient_payable_amount,payment_status,payment_mode,admission_id
0,1,2025-05-26,68483,61634.7,6848.3,Paid,Insurance,1
1,2,2023-11-19,70917,35458.5,35458.5,Paid,Insurance,2
2,3,2023-02-20,28137,25323.3,2813.7,Pending,Insurance,3
3,4,2021-09-01,80665,64532.0,16133.0,Pending,Insurance,4
4,5,2021-07-13,54920,27460.0,27460.0,Pending,Insurance,5

============================================================
billing_detail

   billing_detail_id charge_type  reference_id  amount  bill_id
0                  1        Room          76.0    4884        1
1                  2        Drug           NaN    1844        1
2                  3        Room         302.0   70010        2
3                  4        Test           NaN     562        2
4                  5        Drug           NaN    2489        2

============================================================
department

   department_id    department_name department_type  floor_number  status
0              1          Emergency        Clinical             0  Active
1              2  Internal Medicine        Clinical             2  Active
2              3            Surgery        Clinical             3  Active
3              4         Pediatrics        Clinical             2  Active
4              5        Orthopedics        Clinical             4  Active

============================================================
diagnostic_test

   test_id             test_name test_category  standard_cost  department_id
0        1           X-Ray Chest     Radiology           1328              7
1        2         CT Scan Brain     Radiology           4852              7
2        3             MRI Spine     Radiology           3541              7
3        4    Ultrasound Abdomen     Radiology           1665              7
4        5  Complete Blood Count     Pathology           4257              8

============================================================
disease

   disease_id                 disease_name disease_category
0           1  Acute Myocardial Infarction          Cardiac
1           2                       Stroke     Neurological
2           3        Road Traffic Accident           Trauma
3           4                       Sepsis       Infectious
4           5   Acute Respiratory Distress      Respiratory

============================================================
doctor

   doctor_id  employee_id specialization qualification  experience_years
0          1            3    Orthopedics            DM                31
1          2            9     Pediatrics            MS                 7
2          3           13      Neurology            MS                21
3          4           25        Surgery            MS                25
4          5           26      Neurology          MBBS                 5

============================================================
drug

,drug_id,drug_name,brand_name,drug_category,unit_cost,manufacturer_id
0,1,Earum,Arora-Pandya,Antibiotic,252,44
1,2,Minus,"Bhakta, Dass and Chakraborty",Antipyretic,243,240
2,3,Dolore,Kala Inc,Analgesic,13,215
3,4,Neque,"Bhargava, Andra and Nath",Antacid,356,7
4,5,Tempore,Lalla-Char,Antihypertensive,359,113

============================================================
drug_inventory

,inventory_id,current_stock,reorder_level,inventory_status,last_restock_date,drug_id
0,1,347,170,Normal,2025-04-21,1
1,2,949,125,Normal,2023-03-30,2
2,3,293,246,Normal,2020-02-09,3
3,4,433,252,Normal,2021-03-06,4
4,5,641,114,Normal,2024-02-08,5

============================================================
drug_manufacturer

,manufacturer_id,manufacturer_name,country,reliability_rating,contract_status
0,1,"Dora, Yogi and Deshpande",USA,3.8,Active
1,2,Dhawan-Bhasin,UK,4.4,Expired
2,3,"Trivedi, Chaudhry and Parmar",UK,4.3,Active
3,4,"Chada, Mall and Parmar",Germany,3.9,Expired
4,5,Khanna-Chand,UK,4.5,Expired

============================================================
employee

,employee_id,employee_name,gender,role,employment_type,date_of_joining,department_id
0,1,Sanaya Kalla,Male,Admin,Contract,2024-04-17,11
1,2,Dayamai Raj,Female,Nurse,Full-time,2011-05-09,6
2,3,Logan Lata,Male,Doctor,Contract,2020-10-27,8
3,4,Vyanjana Kota,Female,Technician,Contract,2013-05-01,9
4,5,Nachiket Mani,Female,Admin,Contract,2013-02-16,3

============================================================
insurance_provider

,insurance_provider_id,provider_name,provider_type,contact_details,coverage_limit
0,1,Bhatti Group Health Insurance,Private,312415859,1500000
1,2,"Buch, Sane and Mital Health Insurance",Govt,4725671570,1500000
2,3,Raval-Panchal Health Insurance,Private,3558053298,300000
3,4,Dalal Group Health Insurance,Private,2200795707,200000
4,5,"Sridhar, Upadhyay and Dewan Health Insurance",Private,905244964,300000

============================================================
patient

,patient_id,gender,date_of_birth,blood_group,city,contact_number
0,1,Female,1987-08-24,O-,East Stephanieberg,+1-792-342-0981
1,2,Male,1960-05-18,A-,Manuelbury,793-725-0800
2,3,Male,1955-04-24,A-,Lake Susanchester,+1-330-617-3749x232
3,4,Male,2004-06-16,B-,South Leslieburgh,426-611-6235x07684
4,5,Male,1977-07-22,A-,Lopezchester,(215)330-2831x0821

============================================================
patient_diagnostic

,patient_diagnostic_id,test_date,result_status,admission_id,test_id,doctor_id
0,1,2020-02-25,Normal,1,8,47
1,2,2020-02-25,Normal,1,2,43
2,3,2020-02-27,Abnormal,1,6,3
3,4,2022-03-04,Normal,2,1,3
4,5,2021-02-07,Abnormal,3,9,39

============================================================
patient_insurance

,patient_insurance_id,policy_number,coverage_percentage,policy_start_date,policy_end_date,patient_id,insurance_provider_id
0,1,POL55116683,50,2020-01-01,2022-12-31,2309,39
1,2,POL94717622,80,2022-12-31,2025-12-30,2309,1
2,3,POL90122917,80,2020-01-01,2020-12-31,22405,12
3,4,POL58454937,70,2020-12-31,2023-12-31,22405,17
4,5,POL84239721,50,2020-01-01,2020-12-31,23398,28

============================================================
prescription

,prescription_id,dosage,frequency,duration_days,admission_id,drug_id
0,1,1 tablet,Twice a day,12,1,227
1,2,2 tablet,Twice a day,7,1,70
2,3,2 tablet,Thrice a day,3,1,234
3,4,2 tablet,Once a day,13,1,205
4,5,2 tablet,Twice a day,12,3,145

============================================================
staff_assignment

   assignment_id  employee_id  ward_id    shift
0              1            2       24  Morning
1              2            4        2  Morning
2              3           17       24    Night
3              4           19       12    Night
4              5           20       22  Morning

============================================================
ward

   ward_id         ward_name ward_type  total_beds  department_id
0        1  Emergency Ward 1   General          10              1
1        2  Emergency Ward 2   Private          15              1
2        3  Emergency Ward 3   General          10              1
3        4  Emergency Ward 4   General          20              1
4        5  Emergency Ward 5   General          20              1

In [7]:
for name, df in datasets.items():
    print("=" * 80)
    print(name.upper())
    print(df.columns.tolist())

================================================================================
ADMISSION
['admission_id', 'admission_date', 'discharge_date', 'admission_type', 'admission_status', 'patient_id', 'department_id', 'ward_id', 'bed_id', 'disease_id']
================================================================================
BED
['bed_id', 'bed_number', 'bed_status', 'ward_id']
================================================================================
BILLING
['bill_id', 'bill_date', 'total_amount', 'insurance_covered_amount', 'patient_payable_amount', 'payment_status', 'payment_mode', 'admission_id']
================================================================================
BILLING_DETAIL
['billing_detail_id', 'charge_type', 'reference_id', 'amount', 'bill_id']
================================================================================
DEPARTMENT
['department_id', 'department_name', 'department_type', 'floor_number', 'status']
================================================================================
DIAGNOSTIC_TEST
['test_id', 'test_name', 'test_category', 'standard_cost', 'department_id']
================================================================================
DISEASE
['disease_id', 'disease_name', 'disease_category']
================================================================================
DOCTOR
['doctor_id', 'employee_id', 'specialization', 'qualification', 'experience_years']
================================================================================
DRUG
['drug_id', 'drug_name', 'brand_name', 'drug_category', 'unit_cost', 'manufacturer_id']
================================================================================
DRUG_INVENTORY
['inventory_id', 'current_stock', 'reorder_level', 'inventory_status', 'last_restock_date', 'drug_id']
================================================================================
DRUG_MANUFACTURER
['manufacturer_id', 'manufacturer_name', 'country', 'reliability_rating', 'contract_status']
================================================================================
EMPLOYEE
['employee_id', 'employee_name', 'gender', 'role', 'employment_type', 'date_of_joining', 'department_id']
================================================================================
INSURANCE_PROVIDER
['insurance_provider_id', 'provider_name', 'provider_type', 'contact_details', 'coverage_limit']
================================================================================
PATIENT
['patient_id', 'gender', 'date_of_birth', 'blood_group', 'city', 'contact_number']
================================================================================
PATIENT_DIAGNOSTIC
['patient_diagnostic_id', 'test_date', 'result_status', 'admission_id', 'test_id', 'doctor_id']
================================================================================
PATIENT_INSURANCE
['patient_insurance_id', 'policy_number', 'coverage_percentage', 'policy_start_date', 'policy_end_date', 'patient_id', 'insurance_provider_id']
================================================================================
PRESCRIPTION
['prescription_id', 'dosage', 'frequency', 'duration_days', 'admission_id', 'drug_id']
================================================================================
STAFF_ASSIGNMENT
['assignment_id', 'employee_id', 'ward_id', 'shift']
================================================================================
WARD
['ward_id', 'ward_name', 'ward_type', 'total_beds', 'department_id']

In [8]:
master = admission.copy()

In [9]:
master = master.merge(
    patient,
    on="patient_id",
    how="left"
)

In [10]:
master = master.merge(
    department,
    on="department_id",
    how="left"
)

In [11]:
master = master.merge(
    ward,
    on="ward_id",
    how="left",
    suffixes=('', '_ward')
)

In [12]:
master = master.merge(
    bed,
    on="bed_id",
    how="left"
)

In [13]:
master = master.merge(
    disease,
    on="disease_id",
    how="left"
)

In [14]:
print(master.shape)
master.head()

(45000, 28)

,admission_id,admission_date,discharge_date,admission_type,admission_status,patient_id,department_id,ward_id_x,bed_id,disease_id,...,status,ward_name,ward_type,total_beds,department_id_ward,bed_number,bed_status,ward_id_y,disease_name,disease_category
0,1,2020-02-25,2020-02-27,Emergency,Discharged,166,2,6,76,10,...,Active,Internal Medicine Ward 1,Private,10,2,6-1,Available,6,Anemia,Hematological
1,2,2022-02-22,2022-03-04,Elective,Discharged,8622,5,21,302,11,...,Active,Orthopedics Ward 1,General,15,5,21-2,Available,21,Fracture Femur,Orthopedic
2,3,2021-02-03,2021-02-09,Elective,Discharged,23976,1,2,11,9,...,Active,Emergency Ward 2,Private,15,1,2-1,Available,2,Chronic Obstructive Pulmonary Disease,Respiratory
3,4,2021-12-31,2022-01-05,Elective,Discharged,16635,2,10,128,1,...,Active,Internal Medicine Ward 5,General,20,2,10-8,Available,10,Acute Myocardial Infarction,Cardiac
4,5,2022-07-02,2022-07-07,Elective,Discharged,10654,3,11,157,7,...,Active,Surgery Ward 1,General,20,3,11-17,Available,11,Hypertension,Cardiac

# Data Cleaning

In [15]:
master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   admission_id        45000 non-null  int64
 1   admission_date      45000 non-null  object
 2   discharge_date      45000 non-null  object
 3   admission_type      45000 non-null  object
 4   admission_status    45000 non-null  object
 5   patient_id          45000 non-null  int64
 6   department_id       45000 non-null  int64
 7   ward_id_x           45000 non-null  int64
 8   bed_id              45000 non-null  int64
 9   disease_id          45000 non-null  int64
 10  gender              45000 non-null  object
 11  date_of_birth       45000 non-null  object
 12  blood_group         45000 non-null  object
 13  city                45000 non-null  object
 14  contact_number      45000 non-null  object
 15  department_name     45000 non-null  object
 16  department_type     45000 non-null  object
 17  floor_number        45000 non-null  int64
 18  status              45000 non-null  object
 19  ward_name           45000 non-null  object
 20  ward_type           45000 non-null  object
 21  total_beds          45000 non-null  int64
 22  department_id_ward  45000 non-null  int64
 23  bed_number          45000 non-null  object
 24  bed_status          45000 non-null  object
 25  ward_id_y           45000 non-null  int64
 26  disease_name        45000 non-null  object
 27  disease_category    45000 non-null  object
dtypes: int64(10), object(18)
memory usage: 9.6+ MB

In [16]:
master.isnull().sum()

admission_id          0
admission_date        0
discharge_date        0
admission_type        0
admission_status      0
patient_id            0
department_id         0
ward_id_x             0
bed_id                0
disease_id            0
gender                0
date_of_birth         0
blood_group           0
city                  0
contact_number        0
department_name       0
department_type       0
floor_number          0
status                0
ward_name             0
ward_type             0
total_beds            0
department_id_ward    0
bed_number            0
bed_status            0
ward_id_y             0
disease_name          0
disease_category      0
dtype: int64

In [17]:
print(master.shape)

(45000, 28)

In [18]:
master["admission_date"] = pd.to_datetime(master["admission_date"])
master["discharge_date"] = pd.to_datetime(master["discharge_date"])

master["length_of_stay"] = (
    master["discharge_date"] - master["admission_date"]
).dt.days
master[["admission_date","discharge_date","length_of_stay"]].head()

  admission_date discharge_date  length_of_stay
0     2020-02-25     2020-02-27               2
1     2022-02-22     2022-03-04              10
2     2021-02-03     2021-02-09               6
3     2021-12-31     2022-01-05               5
4     2022-07-02     2022-07-07               5

In [19]:
master.to_csv("Fact_Admissions.csv", index=False)

print("Master Dataset Saved Successfully!")

Master Dataset Saved Successfully!

In [20]:
patient.to_csv("Dim_Patient.csv", index=False)

department.to_csv("Dim_Department.csv", index=False)

doctor.to_csv("Dim_Doctor.csv", index=False)

ward.to_csv("Dim_Ward.csv", index=False)

disease.to_csv("Dim_Disease.csv", index=False)

insurance_provider.to_csv("Dim_Insurance.csv", index=False)

drug.to_csv("Dim_Drug.csv", index=False)

# cleaning

In [21]:
print(master.shape)

master.info()

(45000, 29)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 29 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   admission_id        45000 non-null  int64
 1   admission_date      45000 non-null  datetime64[ns]
 2   discharge_date      45000 non-null  datetime64[ns]
 3   admission_type      45000 non-null  object
 4   admission_status    45000 non-null  object
 5   patient_id          45000 non-null  int64
 6   department_id       45000 non-null  int64
 7   ward_id_x           45000 non-null  int64
 8   bed_id              45000 non-null  int64
 9   disease_id          45000 non-null  int64
 10  gender              45000 non-null  object
 11  date_of_birth       45000 non-null  object
 12  blood_group         45000 non-null  object
 13  city                45000 non-null  object
 14  contact_number      45000 non-null  object
 15  department_name     45000 non-null  object
 16  department_type     45000 non-null  object
 17  floor_number        45000 non-null  int64
 18  status              45000 non-null  object
 19  ward_name           45000 non-null  object
 20  ward_type           45000 non-null  object
 21  total_beds          45000 non-null  int64
 22  department_id_ward  45000 non-null  int64
 23  bed_number          45000 non-null  object
 24  bed_status          45000 non-null  object
 25  ward_id_y           45000 non-null  int64
 26  disease_name        45000 non-null  object
 27  disease_category    45000 non-null  object
 28  length_of_stay      45000 non-null  int64
dtypes: datetime64[ns](2), int64(11), object(16)
memory usage: 10.0+ MB

In [22]:
missing_values = master.isnull().sum()

missing_values = missing_values[missing_values > 0]

print(missing_values)

Series([], dtype: int64)

In [23]:
print("Duplicate Rows:", master.duplicated().sum())

Duplicate Rows: 0

In [24]:
master["admission_date"] = pd.to_datetime(master["admission_date"])
master["discharge_date"] = pd.to_datetime(master["discharge_date"])

In [25]:
master["length_of_stay"] = (
    master["discharge_date"] - master["admission_date"]
).dt.days

In [26]:
master["admission_year"] = master["admission_date"].dt.year

In [27]:
master["admission_month"] = master["admission_date"].dt.month_name()

In [28]:
master["admission_quarter"] = master["admission_date"].dt.quarter

In [29]:
master["admission_day"] = master["admission_date"].dt.day_name()

In [30]:
master[[
    "admission_date",
    "discharge_date",
    "length_of_stay",
    "admission_year",
    "admission_month",
    "admission_quarter",
    "admission_day"
]].head()

,admission_date,discharge_date,length_of_stay,admission_year,admission_month,admission_quarter,admission_day
0,2020-02-25,2020-02-27,2,2020,February,1,Tuesday
1,2022-02-22,2022-03-04,10,2022,February,1,Tuesday
2,2021-02-03,2021-02-09,6,2021,February,1,Wednesday
3,2021-12-31,2022-01-05,5,2021,December,4,Friday
4,2022-07-02,2022-07-07,5,2022,July,3,Saturday

In [31]:
import os

os.makedirs("../Processed_Data", exist_ok=True)

master.to_csv("../Processed_Data/Fact_Admissions.csv", index=False)

print("✅ Fact_Admissions.csv saved successfully!")

✅ Fact_Admissions.csv saved successfully!

In [32]:
master.to_csv("../Processed_Data/Fact_Admissions_Clean.csv", index=False)

In [33]:
columns_to_drop = [
    "ward_id_x",
    "ward_id_y",
    "department_id",
    "department_id_ward",
    "bed_id",
    "disease_id"
]

master = master.drop(columns=columns_to_drop, errors="ignore")

In [34]:
master.to_csv("../Processed_Data/Fact_Admissions_Clean.csv", index=False)

print("✅ Clean dataset saved successfully!")

✅ Clean dataset saved successfully!

In [35]:
master = master.sort_values(["patient_id", "admission_date"])

In [36]:
master["previous_discharge"] = master.groupby("patient_id")["discharge_date"].shift(1)

In [37]:
master["days_after_discharge"] = (
    master["admission_date"] - master["previous_discharge"]
).dt.days

In [38]:
master["readmission"] = master["days_after_discharge"].apply(
    lambda x: "Yes" if pd.notna(x) and x <= 30 else "No"
)

In [39]:
master[[
    "patient_id",
    "admission_date",
    "previous_discharge",
    "days_after_discharge",
    "readmission"
]].head(10)

,patient_id,admission_date,previous_discharge,days_after_discharge,readmission
42491,1,2021-04-09,NaT,NaN,No
39307,1,2022-07-09,2021-04-10,455.0,No
33890,1,2024-03-22,2022-07-11,620.0,No
2174,3,2023-09-08,NaT,NaN,No
43087,3,2024-11-28,2023-09-15,440.0,No
6281,4,2020-04-19,NaT,NaN,No
17215,4,2024-01-10,2020-04-20,1360.0,No
28737,6,2021-12-30,NaT,NaN,No
25976,7,2025-01-13,NaT,NaN,No
11235,8,2023-12-18,NaT,NaN,No

In [41]:
bed_status = (
    master.groupby("bed_status")
          .size()
          .reset_index(name="Beds")
)

bed_status.to_csv("KPI_Data/Bed_Status.csv", index=False)

print(bed_status)

OSError: Cannot save file into a non-existent directory: 'KPI_Data'