In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("hospital_raw_data.csv")

In [3]:
df.head()

,Admission_ID,Patient_ID,Doctor_ID,Department_ID,Admission_Date,Discharge_Date,Admission_Type,Diagnosis,Ward_Type,Room_No,...,Bill_ID,Consultation_Fee,Room_Charges,Medicine_Cost,Lab_Cost,Other_Charges,Total_Amount,Insurance_Covered,Patient_Payable,Payment_Status
0,A000001,P01079,D0026,102,3/1/2026,3/3/2026,Referral,Migraine,General,G-217,...,B000001,1949,9476,11427,5428,4614,32894,26380.12,6513.88,Paid
1,A000002,P00881,D0101,105,12/23/2025,12/29/2025,Emergency,Kidney Stone,Semi-Private,SP-862,...,B000002,1714,21138,5587,5745,2992,37176,0.00,37176.00,Paid
2,A000003,P02567,D0109,105,4/6/2025,4/10/2025,Referral,Diabetes,General,G-994,...,B000003,677,10988,13360,9122,1726,35873,29913.95,5959.05,Paid
3,A000004,P00972,D0088,105,6/25/2025,6/28/2025,Emergency,Diabetes,General,G-995,...,B000004,1927,13008,14982,5167,4781,39865,0.00,39865.00,Paid
4,A000005,P03546,D0030,102,12/25/2024,12/28/2024,Elective,Migraine,General,G-924,...,B000005,769,8256,14757,8915,1938,34635,25962.94,8672.06,Paid

In [4]:
df.shape

(10000, 41)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 41 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Admission_ID        10000 non-null  object
 1   Patient_ID          10000 non-null  object
 2   Doctor_ID           10000 non-null  object
 3   Department_ID       10000 non-null  int64
 4   Admission_Date      10000 non-null  object
 5   Discharge_Date      10000 non-null  object
 6   Admission_Type      10000 non-null  object
 7   Diagnosis           10000 non-null  object
 8   Ward_Type           10000 non-null  object
 9   Room_No             10000 non-null  object
 10  Length_of_Stay      10000 non-null  int64
 11  Status              10000 non-null  object
 12  Patient_First_Name  10000 non-null  object
 13  Patient_Last_Name   10000 non-null  object
 14  Patient_Gender      10000 non-null  object
 15  DOB                 10000 non-null  object
 16  Blood_Group         10000 non-null  object
 17  City                10000 non-null  object
 18  State               10000 non-null  object
 19  Insurance           10000 non-null  object
 20  Insurance_Provider  5078 non-null   object
 21  Doctor_First_Name   10000 non-null  object
 22  Doctor_Last_Name    10000 non-null  object
 23  Doctor_Gender       10000 non-null  object
 24  Qualification       10000 non-null  object
 25  Experience_Years    10000 non-null  int64
 26  Salary              10000 non-null  int64
 27  Department_Name     10000 non-null  object
 28  Total_Beds          10000 non-null  int64
 29  Doctors             10000 non-null  int64
 30  Nurses              10000 non-null  int64
 31  Bill_ID             10000 non-null  object
 32  Consultation_Fee    10000 non-null  int64
 33  Room_Charges        10000 non-null  int64
 34  Medicine_Cost       10000 non-null  int64
 35  Lab_Cost            10000 non-null  int64
 36  Other_Charges       10000 non-null  int64
 37  Total_Amount        10000 non-null  int64
 38  Insurance_Covered   10000 non-null  float64
 39  Patient_Payable     10000 non-null  float64
 40  Payment_Status      10000 non-null  object
dtypes: float64(2), int64(13), object(26)
memory usage: 3.1+ MB

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.isnull().sum()

Admission_ID             0
Patient_ID               0
Doctor_ID                0
Department_ID            0
Admission_Date           0
Discharge_Date           0
Admission_Type           0
Diagnosis                0
Ward_Type                0
Room_No                  0
Length_of_Stay           0
Status                   0
Patient_First_Name       0
Patient_Last_Name        0
Patient_Gender           0
DOB                      0
Blood_Group              0
City                     0
State                    0
Insurance                0
Insurance_Provider    4922
Doctor_First_Name        0
Doctor_Last_Name         0
Doctor_Gender            0
Qualification            0
Experience_Years         0
Salary                   0
Department_Name          0
Total_Beds               0
Doctors                  0
Nurses                   0
Bill_ID                  0
Consultation_Fee         0
Room_Charges             0
Medicine_Cost            0
Lab_Cost                 0
Other_Charges            0
Total_Amount             0
Insurance_Covered        0
Patient_Payable          0
Payment_Status           0
dtype: int64

In [8]:
df["Insurance"].value_counts()

Insurance
Yes    5078
No     4922
Name: count, dtype: int64

In [9]:
df["Insurance_Provider"] = df["Insurance_Provider"].fillna("Not Insured")

In [10]:
df["Insurance_Provider"].isnull().sum()

np.int64(0)

In [11]:
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"])
df["Discharge_Date"] = pd.to_datetime(df["Discharge_Date"])
df["DOB"] = pd.to_datetime(df["DOB"])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 41 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Admission_ID        10000 non-null  object
 1   Patient_ID          10000 non-null  object
 2   Doctor_ID           10000 non-null  object
 3   Department_ID       10000 non-null  int64
 4   Admission_Date      10000 non-null  datetime64[ns]
 5   Discharge_Date      10000 non-null  datetime64[ns]
 6   Admission_Type      10000 non-null  object
 7   Diagnosis           10000 non-null  object
 8   Ward_Type           10000 non-null  object
 9   Room_No             10000 non-null  object
 10  Length_of_Stay      10000 non-null  int64
 11  Status              10000 non-null  object
 12  Patient_First_Name  10000 non-null  object
 13  Patient_Last_Name   10000 non-null  object
 14  Patient_Gender      10000 non-null  object
 15  DOB                 10000 non-null  datetime64[ns]
 16  Blood_Group         10000 non-null  object
 17  City                10000 non-null  object
 18  State               10000 non-null  object
 19  Insurance           10000 non-null  object
 20  Insurance_Provider  10000 non-null  object
 21  Doctor_First_Name   10000 non-null  object
 22  Doctor_Last_Name    10000 non-null  object
 23  Doctor_Gender       10000 non-null  object
 24  Qualification       10000 non-null  object
 25  Experience_Years    10000 non-null  int64
 26  Salary              10000 non-null  int64
 27  Department_Name     10000 non-null  object
 28  Total_Beds          10000 non-null  int64
 29  Doctors             10000 non-null  int64
 30  Nurses              10000 non-null  int64
 31  Bill_ID             10000 non-null  object
 32  Consultation_Fee    10000 non-null  int64
 33  Room_Charges        10000 non-null  int64
 34  Medicine_Cost       10000 non-null  int64
 35  Lab_Cost            10000 non-null  int64
 36  Other_Charges       10000 non-null  int64
 37  Total_Amount        10000 non-null  int64
 38  Insurance_Covered   10000 non-null  float64
 39  Patient_Payable     10000 non-null  float64
 40  Payment_Status      10000 non-null  object
dtypes: datetime64[ns](3), float64(2), int64(13), object(23)
memory usage: 3.1+ MB

In [13]:
df["Department_Name"].unique()

array(['Neurology', 'General Medicine', 'Orthopedics', 'Cardiology',
       'Surgery', 'Oncology', 'Emergency'], dtype=object)

In [14]:
today = pd.Timestamp.today()

df["Age"] = ((today - df["DOB"]).dt.days // 365)

In [15]:
df[["DOB", "Age"]].head()

         DOB  Age
0 1994-10-01   31
1 1949-02-13   77
2 1935-11-01   90
3 1985-12-01   40
4 1976-01-28   50

In [16]:
df.to_csv("hospital_cleaned.csv", index=False)