In [ ]:
import pandas as pd

df = pd.read_csv("../data/processed/hospital_raw_data.csv")

(45000, 58)

In [ ]:
drop_cols = [
    "provider_type",
    "patient_insurance_id",
    "contact_details",
    "policy_start_date",
    "policy_end_date",
    "insurance_provider_id"
]

df.drop(
    columns=[c for c in drop_cols if c in df.columns],
    inplace=True
)

print(df.shape)

(45000, 52)

In [ ]:
import pandas as pd

df = pd.read_csv("../data/cleaned/hospital_cleaned.csv")

print(df.shape)

(45000, 58)

In [ ]:
import pandas as pd

df = pd.read_csv("../data/cleaned/hospital_cleaned.csv")

print(df.shape)

(45000, 58)

In [ ]:
df = pd.read_csv("../data/cleaned/hospital_cleaned.csv")
print(df.shape)

(45000, 58)

In [ ]:
df_clean = df.copy()

In [ ]:
print("Duplicates before:", df_clean.duplicated().sum())

df_clean.drop_duplicates(inplace=True)

print("Duplicates after:", df_clean.duplicated().sum())

Duplicates before: 534
Duplicates after: 0

In [ ]:
import os
import pandas as pd

BASE_DIR = r"D:\MedTrack_DV"

file_path = os.path.join(BASE_DIR, "data", "processed", "fact_admissions.csv")

df = pd.read_csv(file_path)

print(df.columns)
print(df.shape)

Index(['admission_id', 'admission_date', 'discharge_date', 'admission_type',
       'admission_status', 'patient_id', 'department_id', 'ward_id', 'bed_id',
       'disease_id', 'total_amount', 'patient_payable_amount'],
      dtype='str')
(45000, 12)

In [ ]:
import sys

print(sys.executable)

d:\MedTrack_DV\.venv\Scripts\python.exe

In [ ]:
import os

print(os.getcwd())

d:\MedTrack_DV\notebooks

In [ ]:
df.shape

(45000, 59)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 59 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   admission_id              45000 non-null  int64
 1   admission_date            45000 non-null  str
 2   discharge_date            45000 non-null  str
 3   admission_type            45000 non-null  str
 4   admission_status          45000 non-null  str
 5   patient_id                45000 non-null  int64
 6   department_id             45000 non-null  int64
 7   ward_id                   45000 non-null  int64
 8   bed_id                    45000 non-null  int64
 9   disease_id                45000 non-null  int64
 10  gender                    45000 non-null  str
 11  date_of_birth             45000 non-null  str
 12  blood_group               45000 non-null  str
 13  city                      45000 non-null  str
 14  contact_number            45000 non-null  str
 15  department_name           45000 non-null  str
 16  department_type           45000 non-null  str
 17  floor_number              45000 non-null  int64
 18  status                    45000 non-null  str
 19  ward_name                 45000 non-null  str
 20  ward_type                 45000 non-null  str
 21  total_beds                45000 non-null  int64
 22  bed_number                45000 non-null  str
 23  bed_status                45000 non-null  str
 24  disease_name              45000 non-null  str
 25  disease_category          45000 non-null  str
 26  bill_id                   45000 non-null  int64
 27  bill_date                 45000 non-null  str
 28  total_amount              45000 non-null  int64
 29  insurance_covered_amount  45000 non-null  float64
 30  patient_payable_amount    45000 non-null  float64
 31  payment_status            45000 non-null  str
 32  payment_mode              45000 non-null  str
 33  patient_insurance_id      45000 non-null  float64
 34  policy_number             45000 non-null  str
 35  coverage_percentage       45000 non-null  float64
 36  policy_start_date         45000 non-null  str
 37  policy_end_date           45000 non-null  str
 38  insurance_provider_id     45000 non-null  float64
 39  provider_name             45000 non-null  str
 40  provider_type             27111 non-null  str
 41  contact_details           27111 non-null  float64
 42  coverage_limit            45000 non-null  float64
 43  length_of_stay            45000 non-null  int64
 44  patient_age               45000 non-null  int64
 45  age_group                 45000 non-null  str
 46  insurance_status          45000 non-null  str
 47  revenue_category          45000 non-null  str
 48  admission_year            45000 non-null  int64
 49  admission_month           45000 non-null  str
 50  admission_month_number    45000 non-null  int64
 51  admission_year_month      45000 non-null  str
 52  admission_quarter         45000 non-null  str
 53  emergency_flag            45000 non-null  int64
 54  stay_category             45000 non-null  str
 55  department_revenue        45000 non-null  int64
 56  disease_load              45000 non-null  int64
 57  disease_load_category     45000 non-null  str
 58  bed_occupancy_flag        45000 non-null  int64
dtypes: float64(7), int64(18), str(34)
memory usage: 20.3 MB

In [ ]:
df.shape

(45000, 59)

In [ ]:
missing = df.isnull().sum()

missing[missing > 0]

provider_type      17889
contact_details    17889
dtype: int64

In [ ]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage[missing_percentage > 0]

provider_type      39.753333
contact_details    39.753333
dtype: float64

In [ ]:
df['provider_type'] = df['provider_type'].fillna("Unknown")

In [ ]:
df = df.drop(columns=['contact_details'])

In [ ]:
missing = df.isnull().sum()

missing[missing > 0]

Series([], dtype: int64)

In [ ]:
df.to_csv("../data/cleaned/hospital_cleaned.csv", index=False)

In [ ]:
df.shape

(45000, 58)

In [ ]:
df['admission_type'].value_counts()

admission_type
Elective     26923
Emergency    18077
Name: count, dtype: int64

In [ ]:
df['admission_status'].value_counts()

admission_status
Discharged    45000
Name: count, dtype: int64

In [ ]:
df['department_name'].value_counts().head(10)

department_name
Surgery              10126
Emergency             8777
Pediatrics            8438
Internal Medicine     7695
Orthopedics           5924
ICU                   4040
Name: count, dtype: int64

In [ ]:
df['bed_status'].value_counts()

bed_status
Available    45000
Name: count, dtype: int64

In [ ]:
df['ward_name'].value_counts().head(10)

ward_name
Pediatrics Ward 2           2228
Emergency Ward 4            2227
Emergency Ward 5            2212
Orthopedics Ward 3          2207
Internal Medicine Ward 5    2168
Surgery Ward 2              2157
Surgery Ward 3              2147
Surgery Ward 1              2140
Surgery Ward 4              1895
Pediatrics Ward 3           1881
Name: count, dtype: int64

In [ ]:
df['disease_name'].value_counts().head(10)

disease_name
Stroke                                   2300
Sepsis                                   2297
Chronic Obstructive Pulmonary Disease    2289
Fracture Femur                           2288
Acute Myocardial Infarction              2282
Acute Respiratory Distress               2275
Gallstones                               2271
Urinary Tract Infection                  2259
Tuberculosis                             2256
Road Traffic Accident                    2253
Name: count, dtype: int64

In [ ]:
df['disease_category'].value_counts()

disease_category
Infectious       11248
Surgical          6711
Respiratory       4564
Cardiac           4525
Pediatric         4436
Neurological      2300
Orthopedic        2288
Trauma            2253
Renal             2251
Hematological     2235
Endocrine         2189
Name: count, dtype: int64

In [ ]:
df['disease_category'].value_counts()

disease_category
Infectious       11248
Surgical          6711
Respiratory       4564
Cardiac           4525
Pediatric         4436
Neurological      2300
Orthopedic        2288
Trauma            2253
Renal             2251
Hematological     2235
Endocrine         2189
Name: count, dtype: int64

In [ ]:
df['gender'].value_counts()

gender
Male      24031
Female    20058
Other       911
Name: count, dtype: int64

In [ ]:
df['disease_category'].nunique()

11

In [ ]:
df.to_csv("../data/processed/hospital_dashboard_data.csv", index=False)

In [ ]:
department_summary = (
    df.groupby('department_name')
    .agg(
        total_admissions=('admission_id','count'),
        total_wards=('ward_name','nunique'),
        total_diseases=('disease_name','nunique')
    )
    .reset_index()
)

department_summary

     department_name  total_admissions  total_wards  total_diseases
0          Emergency              8777            5              20
1                ICU              4040            4              20
2  Internal Medicine              7695            5              20
3        Orthopedics              5924            3              20
4         Pediatrics              8438            5              20
5            Surgery             10126            5              20

In [ ]:
department_summary.to_csv(
    "../data/processed/department_summary.csv",
    index=False
)

In [ ]:
disease_summary = (
    df.groupby(['disease_category'])
    .agg(
        total_cases=('admission_id','count'),
        unique_diseases=('disease_name','nunique')
    )
    .reset_index()
)

disease_summary

   disease_category  total_cases  unique_diseases
0           Cardiac         4525                2
1         Endocrine         2189                1
2     Hematological         2235                1
3        Infectious        11248                5
4      Neurological         2300                1
5        Orthopedic         2288                1
6         Pediatric         4436                2
7             Renal         2251                1
8       Respiratory         4564                2
9          Surgical         6711                3
10           Trauma         2253                1

In [ ]:
disease_summary = (
    df.groupby(['disease_category'])
    .agg(
        total_cases=('admission_id','count'),
        unique_diseases=('disease_name','nunique')
    )
    .reset_index()
)

disease_summary

   disease_category  total_cases  unique_diseases
0           Cardiac         4525                2
1         Endocrine         2189                1
2     Hematological         2235                1
3        Infectious        11248                5
4      Neurological         2300                1
5        Orthopedic         2288                1
6         Pediatric         4436                2
7             Renal         2251                1
8       Respiratory         4564                2
9          Surgical         6711                3
10           Trauma         2253                1

In [ ]:
disease_summary.to_csv(
    "../data/processed/disease_summary.csv",
    index=False
)

In [ ]:
df.isnull().sum()[df.isnull().sum() > 0]

Series([], dtype: int64)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [1]:
import pandas as pd

path = r"D:\MedTrack_DV\data\cleaned\hospital_cleaned.csv"

df = pd.read_csv(path)

print("Shape:", df.shape)
print("Number of columns:", len(df.columns))
print("First admission_id:", df.iloc[0]["admission_id"])
print(df.columns.tolist())

Shape: (45000, 52)
Number of columns: 52
First admission_id: 10703
['admission_id', 'admission_date', 'discharge_date', 'admission_type', 'admission_status', 'patient_id', 'department_id', 'ward_id', 'bed_id', 'disease_id', 'gender', 'date_of_birth', 'blood_group', 'city', 'contact_number', 'department_name', 'department_type', 'floor_number', 'status', 'ward_name', 'ward_type', 'total_beds', 'bed_number', 'bed_status', 'disease_name', 'disease_category', 'bill_id', 'bill_date', 'total_amount', 'insurance_covered_amount', 'patient_payable_amount', 'payment_status', 'payment_mode', 'policy_number', 'coverage_percentage', 'provider_name', 'coverage_limit', 'length_of_stay', 'patient_age', 'age_group', 'insurance_status', 'revenue_category', 'admission_year', 'admission_month', 'admission_month_number', 'admission_year_month', 'admission_quarter', 'emergency_flag', 'stay_category', 'department_revenue', 'disease_load', 'bed_occupancy_flag']

In [2]:
import pandas as pd

df = pd.read_csv(r"D:\MedTrack_DV\data\cleaned\hospital_cleaned.csv")

print(df.shape)

(45000, 52)

In [4]:
import pandas as pd

df = pd.read_csv("../data/cleaned/hospital_cleaned.csv")
df.info()
df.describe()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 52 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   admission_id              45000 non-null  int64
 1   admission_date            45000 non-null  str
 2   discharge_date            45000 non-null  str
 3   admission_type            45000 non-null  str
 4   admission_status          45000 non-null  str
 5   patient_id                45000 non-null  int64
 6   department_id             45000 non-null  int64
 7   ward_id                   45000 non-null  int64
 8   bed_id                    45000 non-null  int64
 9   disease_id                45000 non-null  int64
 10  gender                    45000 non-null  str
 11  date_of_birth             45000 non-null  str
 12  blood_group               45000 non-null  str
 13  city                      45000 non-null  str
 14  contact_number            45000 non-null  str
 15  department_name           45000 non-null  str
 16  department_type           45000 non-null  str
 17  floor_number              45000 non-null  int64
 18  status                    45000 non-null  str
 19  ward_name                 45000 non-null  str
 20  ward_type                 45000 non-null  str
 21  total_beds                45000 non-null  int64
 22  bed_number                45000 non-null  str
 23  bed_status                45000 non-null  str
 24  disease_name              45000 non-null  str
 25  disease_category          45000 non-null  str
 26  bill_id                   45000 non-null  int64
 27  bill_date                 45000 non-null  str
 28  total_amount              45000 non-null  int64
 29  insurance_covered_amount  45000 non-null  float64
 30  patient_payable_amount    45000 non-null  float64
 31  payment_status            45000 non-null  str
 32  payment_mode              45000 non-null  str
 33  policy_number             45000 non-null  str
 34  coverage_percentage       45000 non-null  float64
 35  provider_name             45000 non-null  str
 36  coverage_limit            45000 non-null  float64
 37  length_of_stay            45000 non-null  int64
 38  patient_age               45000 non-null  int64
 39  age_group                 45000 non-null  str
 40  insurance_status          45000 non-null  str
 41  revenue_category          45000 non-null  str
 42  admission_year            45000 non-null  int64
 43  admission_month           45000 non-null  str
 44  admission_month_number    45000 non-null  int64
 45  admission_year_month      45000 non-null  str
 46  admission_quarter         45000 non-null  str
 47  emergency_flag            45000 non-null  int64
 48  stay_category             45000 non-null  str
 49  department_revenue        45000 non-null  int64
 50  disease_load              45000 non-null  int64
 51  bed_occupancy_flag        45000 non-null  int64
dtypes: float64(4), int64(18), str(30)
memory usage: 17.9 MB

np.int64(0)

In [5]:
df.describe(include="all")
df.isnull().sum().sort_values(ascending=False)
df.duplicated().sum()
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
df.dtypes

Rows: 45000
Columns: 52

admission_id                  int64
admission_date                  str
discharge_date                  str
admission_type                  str
admission_status                str
patient_id                    int64
department_id                 int64
ward_id                       int64
bed_id                        int64
disease_id                    int64
gender                          str
date_of_birth                   str
blood_group                     str
city                            str
contact_number                  str
department_name                 str
department_type                 str
floor_number                  int64
status                          str
ward_name                       str
ward_type                       str
total_beds                    int64
bed_number                      str
bed_status                      str
disease_name                    str
disease_category                str
bill_id                       int64
bill_date                       str
total_amount                  int64
insurance_covered_amount    float64
patient_payable_amount      float64
payment_status                  str
payment_mode                    str
policy_number                   str
coverage_percentage         float64
provider_name                   str
coverage_limit              float64
length_of_stay                int64
patient_age                   int64
age_group                       str
insurance_status                str
revenue_category                str
admission_year                int64
admission_month                 str
admission_month_number        int64
admission_year_month            str
admission_quarter               str
emergency_flag                int64
stay_category                   str
department_revenue            int64
disease_load                  int64
bed_occupancy_flag            int64
dtype: object