In [1]:
import pandas as pd
import numpy as np

In [2]:
path = "../data/processed/hospital_raw_data.csv"

df = pd.read_csv(path)

print(df.shape)
df.head()

(45000, 59)

,admission_id,admission_date,discharge_date,admission_type,admission_status,patient_id,department_id,ward_id,bed_id,disease_id,...,admission_month,admission_month_number,admission_year_month,admission_quarter,emergency_flag,stay_category,department_revenue,disease_load,disease_load_category,bed_occupancy_flag
0,14359,2020-01-01,2020-01-09,Elective,Discharged,4363,1,4,55,17,...,January,1,2020-01,Q1,0,Long Stay,46901,2259,Medium Load,1
1,35859,2020-01-01,2020-01-05,Elective,Discharged,27618,3,13,195,16,...,January,1,2020-01,Q1,0,Medium Stay,46995,2239,Medium Load,1
2,27675,2020-01-01,2020-01-08,Elective,Discharged,24074,1,5,59,10,...,January,1,2020-01,Q1,0,Medium Stay,22593,2235,Medium Load,1
3,1943,2020-01-01,2020-01-11,Elective,Discharged,27854,1,1,7,4,...,January,1,2020-01,Q1,0,Long Stay,71460,2297,High Load,1
4,21236,2020-01-01,2020-01-03,Emergency,Discharged,18799,1,3,32,5,...,January,1,2020-01,Q1,1,Short Stay,29011,2275,High Load,1

In [3]:
missing = df.isnull().sum()

missing[missing > 0]

provider_type      17889
contact_details    17889
dtype: int64

In [4]:
print("Before:", df.shape)

df = df.drop_duplicates()

print("After:", df.shape)

Before: (45000, 59)
After: (45000, 59)

In [5]:
patient_cols = [
    "gender",
    "date_of_birth",
    "blood_group",
    "city",
    "contact_number"
]

for col in patient_cols:
    df[col] = df[col].fillna("Unknown")

In [6]:
output = "../data/cleaned/hospital_cleaned.csv"

df.to_csv(output,index=False)

print("Clean file created")

Clean file created

In [7]:
missing_percent = (df.isnull().sum() / len(df)) * 100

missing_percent[
    missing_percent > 0
]

provider_type      39.753333
contact_details    39.753333
dtype: float64

In [8]:
insurance_cols = [
    "provider_type",
    "contact_details"
]

for col in insurance_cols:
    df[col] = df[col].fillna("Unknown")

In [9]:
df[insurance_cols].isnull().sum()

provider_type      0
contact_details    0
dtype: int64

In [10]:
print("Before:", df.shape)

df = df.drop_duplicates()

print("After:", df.shape)

Before: (45000, 59)
After: (45000, 59)

In [11]:
df.isnull().sum().sort_values(ascending=False).head(10)

admission_id        0
admission_date      0
discharge_date      0
admission_type      0
admission_status    0
patient_id          0
department_id       0
ward_id             0
bed_id              0
disease_id          0
dtype: int64

In [12]:
df.isnull().sum().sum()

np.int64(0)

In [13]:
df["department_name"].value_counts()

department_name
Surgery              10126
Emergency             8777
Pediatrics            8438
Internal Medicine     7695
Orthopedics           5924
ICU                   4040
Name: count, dtype: int64

In [14]:
df.isnull().sum().sum()

np.int64(0)

In [15]:
df.columns.tolist()

['admission_id',
 'admission_date',
 'discharge_date',
 'admission_type',
 'admission_status',
 'patient_id',
 'department_id',
 'ward_id',
 'bed_id',
 'disease_id',
 'gender',
 'date_of_birth',
 'blood_group',
 'city',
 'contact_number',
 'department_name',
 'department_type',
 'floor_number',
 'status',
 'ward_name',
 'ward_type',
 'total_beds',
 'bed_number',
 'bed_status',
 'disease_name',
 'disease_category',
 'bill_id',
 'bill_date',
 'total_amount',
 'insurance_covered_amount',
 'patient_payable_amount',
 'payment_status',
 'payment_mode',
 'patient_insurance_id',
 'policy_number',
 'coverage_percentage',
 'policy_start_date',
 'policy_end_date',
 'insurance_provider_id',
 'provider_name',
 'provider_type',
 'contact_details',
 'coverage_limit',
 'length_of_stay',
 'patient_age',
 'age_group',
 'insurance_status',
 'revenue_category',
 'admission_year',
 'admission_month',
 'admission_month_number',
 'admission_year_month',
 'admission_quarter',
 'emergency_flag',
 'stay_category',
 'department_revenue',
 'disease_load',
 'disease_load_category',
 'bed_occupancy_flag']

In [16]:
categorical_cols = [
    "admission_type",
    "admission_status",
    "department_name",
    "department_type",
    "bed_status",
    "stay_category",
    "disease_load_category",
    "bed_occupancy_flag"
]

for col in categorical_cols:
    print("\n", col)
    print(df[col].unique())

 admission_type
<StringArray>
['Elective', 'Emergency']
Length: 2, dtype: str

 admission_status
<StringArray>
['Discharged']
Length: 1, dtype: str

 department_name
<StringArray>
['Emergency', 'Surgery', 'Pediatrics', 'Internal Medicine', 'Orthopedics',
 'ICU']
Length: 6, dtype: str

 department_type
<StringArray>
['Clinical']
Length: 1, dtype: str

 bed_status
<StringArray>
['Available']
Length: 1, dtype: str

 stay_category
<StringArray>
['Long Stay', 'Medium Stay', 'Short Stay']
Length: 3, dtype: str

 disease_load_category
<StringArray>
['Medium Load', 'High Load', 'Low Load']
Length: 3, dtype: str

 bed_occupancy_flag
[1]

In [17]:
df["bed_status"].value_counts()

bed_status
Available    45000
Name: count, dtype: int64

In [18]:
numeric_cols = [
    "total_beds",
    "department_revenue",
    "disease_load"
]

df[numeric_cols].describe()

         total_beds  department_revenue  disease_load
count  45000.000000        45000.000000  45000.000000
mean      16.194222        37427.691311   2250.538356
std        3.846462        20898.321091     34.661347
min       10.000000         5001.000000   2184.000000
25%       15.000000        21231.000000   2239.000000
50%       15.000000        34623.500000   2253.000000
75%       20.000000        48039.250000   2282.000000
max       20.000000        89990.000000   2300.000000

In [19]:
df.to_csv("hospital_cleaned.csv", index=False)

In [20]:
df.to_csv("hospital_cleaned.csv", index=False)

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 59 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   admission_id              45000 non-null  int64
 1   admission_date            45000 non-null  str
 2   discharge_date            45000 non-null  str
 3   admission_type            45000 non-null  str
 4   admission_status          45000 non-null  str
 5   patient_id                45000 non-null  int64
 6   department_id             45000 non-null  int64
 7   ward_id                   45000 non-null  int64
 8   bed_id                    45000 non-null  int64
 9   disease_id                45000 non-null  int64
 10  gender                    45000 non-null  str
 11  date_of_birth             45000 non-null  str
 12  blood_group               45000 non-null  str
 13  city                      45000 non-null  str
 14  contact_number            45000 non-null  str
 15  department_name           45000 non-null  str
 16  department_type           45000 non-null  str
 17  floor_number              45000 non-null  int64
 18  status                    45000 non-null  str
 19  ward_name                 45000 non-null  str
 20  ward_type                 45000 non-null  str
 21  total_beds                45000 non-null  int64
 22  bed_number                45000 non-null  str
 23  bed_status                45000 non-null  str
 24  disease_name              45000 non-null  str
 25  disease_category          45000 non-null  str
 26  bill_id                   45000 non-null  int64
 27  bill_date                 45000 non-null  str
 28  total_amount              45000 non-null  int64
 29  insurance_covered_amount  45000 non-null  float64
 30  patient_payable_amount    45000 non-null  float64
 31  payment_status            45000 non-null  str
 32  payment_mode              45000 non-null  str
 33  patient_insurance_id      45000 non-null  float64
 34  policy_number             45000 non-null  str
 35  coverage_percentage       45000 non-null  float64
 36  policy_start_date         45000 non-null  str
 37  policy_end_date           45000 non-null  str
 38  insurance_provider_id     45000 non-null  float64
 39  provider_name             45000 non-null  str
 40  provider_type             45000 non-null  str
 41  contact_details           45000 non-null  object
 42  coverage_limit            45000 non-null  float64
 43  length_of_stay            45000 non-null  int64
 44  patient_age               45000 non-null  int64
 45  age_group                 45000 non-null  str
 46  insurance_status          45000 non-null  str
 47  revenue_category          45000 non-null  str
 48  admission_year            45000 non-null  int64
 49  admission_month           45000 non-null  str
 50  admission_month_number    45000 non-null  int64
 51  admission_year_month      45000 non-null  str
 52  admission_quarter         45000 non-null  str
 53  emergency_flag            45000 non-null  int64
 54  stay_category             45000 non-null  str
 55  department_revenue        45000 non-null  int64
 56  disease_load              45000 non-null  int64
 57  disease_load_category     45000 non-null  str
 58  bed_occupancy_flag        45000 non-null  int64
dtypes: float64(6), int64(18), object(1), str(34)
memory usage: 20.3+ MB

In [22]:
df.to_csv("hospital_cleaned.csv", index=False)

In [23]:
import os

print(os.path.exists("hospital_cleaned.csv"))

True

In [24]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())

Rows: 45000
Columns: 59
Missing Values: 0
Duplicate Rows: 0

In [25]:
df = df.drop_duplicates()

In [26]:
print("Rows after removing duplicates:", df.shape[0])
print("Duplicate Rows:", df.duplicated().sum())

Rows after removing duplicates: 45000
Duplicate Rows: 0

In [27]:
df.to_csv("hospital_cleaned.csv", index=False)

In [28]:
import os

print(os.path.exists("hospital_cleaned.csv"))

True

In [ ]:
import pandas as pd
import numpy as np
import os

In [1]:
BASE_DIR = os.path.dirname(os.path.dirname(os.getcwd()))

RAW_PATH = os.path.join(
    BASE_DIR,
    "data",
    "processed",
    "hospital_raw_data.csv"
)

df = pd.read_csv(RAW_PATH)

df.head()

NameError: name 'os' is not defined