In [1]:
import pandas as pd
import numpy as np
import random
from faker import Faker
from datetime import datetime, timedelta

In [2]:
fake = Faker("en_IN")

random.seed(42)
np.random.seed(42)
Faker.seed(42)

In [3]:
NUM_PATIENTS = 5000
NUM_DOCTORS = 150
NUM_NURSES = 300
NUM_ADMISSIONS = 10000

In [4]:
df_departments = pd.DataFrame()
df_doctors = pd.DataFrame()
df_patients = pd.DataFrame()
df_admissions = pd.DataFrame()
df_billing = pd.DataFrame()
df_nurses = pd.DataFrame()

In [5]:
print("Environment Ready ✅")

Environment Ready ✅

In [6]:
department_data = {
    "Department_ID": [101, 102, 103, 104, 105, 106, 107],
    "Department_Name": [
        "Cardiology",
        "Neurology",
        "Orthopedics",
        "Emergency",
        "General Medicine",
        "Surgery",
        "Oncology"
    ],
    "Total_Beds": [60, 45, 55, 80, 120, 70, 40],
    "Doctors": [20, 15, 18, 25, 40, 22, 10],
    "Nurses": [35, 28, 30, 50, 70, 45, 20]
}

df_departments = pd.DataFrame(department_data)

df_departments

   Department_ID   Department_Name  Total_Beds  Doctors  Nurses
0            101        Cardiology          60       20      35
1            102         Neurology          45       15      28
2            103       Orthopedics          55       18      30
3            104         Emergency          80       25      50
4            105  General Medicine         120       40      70
5            106           Surgery          70       22      45
6            107          Oncology          40       10      20

In [7]:
print(df_departments.shape)

(7, 5)

In [8]:
df_departments.to_csv("data/departments.csv", index=False)

In [9]:
pd.read_csv("data/departments.csv").head()

   Department_ID   Department_Name  Total_Beds  Doctors  Nurses
0            101        Cardiology          60       20      35
1            102         Neurology          45       15      28
2            103       Orthopedics          55       18      30
3            104         Emergency          80       25      50
4            105  General Medicine         120       40      70

In [10]:
doctor_distribution = {
    101: 20,   # Cardiology
    102: 15,   # Neurology
    103: 18,   # Orthopedics
    104: 25,   # Emergency
    105: 40,   # General Medicine
    106: 22,   # Surgery
    107: 10    # Oncology
}

In [12]:
qualification_map = {
    "Cardiology": "DM Cardiology",
    "Neurology": "DM Neurology",
    "Orthopedics": "MS Orthopedics",
    "Emergency": "MD Emergency Medicine",
    "General Medicine": "MD General Medicine",
    "Surgery": "MS General Surgery",
    "Oncology": "DM Oncology"
}

In [13]:
doctors = []

doctor_number = 1

for _, dept in df_departments.iterrows():

    dept_id = dept["Department_ID"]
    dept_name = dept["Department_Name"]

    for i in range(doctor_distribution[dept_id]):

        gender = random.choice(["Male", "Female"])

        if gender == "Male":
            first = fake.first_name_male()
        else:
            first = fake.first_name_female()

        last = fake.last_name()

        experience = random.randint(2, 30)

        salary = random.randint(80000, 300000)

        doctors.append({

            "Doctor_ID": f"D{doctor_number:04}",

            "Doctor_First_Name": first,

            "Doctor_Last_Name": last,

            "Gender": gender,

            "Department_ID": dept_id,

            "Department_Name": dept_name,

            "Qualification": qualification_map[dept_name],

            "Experience_Years": experience,

            "Salary": salary,

            "Phone": fake.phone_number(),

            "Email": f"{first.lower()}.{last.lower()}@hospital.com"

        })

        doctor_number += 1

In [14]:
df_doctors = pd.DataFrame(doctors)

df_doctors.head()

,Doctor_ID,Doctor_First_Name,Doctor_Last_Name,Gender,Department_ID,Department_Name,Qualification,Experience_Years,Salary,Phone,Email
0,D0001,Daksh,Bakshi,Male,101,Cardiology,DM Cardiology,2,274393,4332181960,daksh.bakshi@hospital.com
1,D0002,Amruta,Chander,Female,101,Cardiology,DM Cardiology,9,138513,+913890838637,amruta.chander@hospital.com
2,D0003,Liam,Ahuja,Male,101,Cardiology,DM Cardiology,25,106868,+916542351161,liam.ahuja@hospital.com
3,D0004,Praneel,Padmanabhan,Male,101,Cardiology,DM Cardiology,20,190604,4078161849,praneel.padmanabhan@hospital.com
4,D0005,Pratyush,Handa,Male,101,Cardiology,DM Cardiology,2,104561,1034131647,pratyush.handa@hospital.com

In [15]:
print(df_doctors.shape)

(150, 11)

In [16]:
df_doctors["Qualification"].unique()

array(['DM Cardiology', 'DM Neurology', 'MS Orthopedics',
       'MD Emergency Medicine', 'MD General Medicine',
       'MS General Surgery', 'DM Oncology'], dtype=object)

In [17]:
df_doctors.to_csv("data/doctors.csv", index=False)

In [18]:
pd.read_csv("data/doctors.csv").head()

,Doctor_ID,Doctor_First_Name,Doctor_Last_Name,Gender,Department_ID,Department_Name,Qualification,Experience_Years,Salary,Phone,Email
0,D0001,Daksh,Bakshi,Male,101,Cardiology,DM Cardiology,2,274393,4332181960,daksh.bakshi@hospital.com
1,D0002,Amruta,Chander,Female,101,Cardiology,DM Cardiology,9,138513,913890838637,amruta.chander@hospital.com
2,D0003,Liam,Ahuja,Male,101,Cardiology,DM Cardiology,25,106868,916542351161,liam.ahuja@hospital.com
3,D0004,Praneel,Padmanabhan,Male,101,Cardiology,DM Cardiology,20,190604,4078161849,praneel.padmanabhan@hospital.com
4,D0005,Pratyush,Handa,Male,101,Cardiology,DM Cardiology,2,104561,1034131647,pratyush.handa@hospital.com

In [19]:
blood_groups = [
    "A+","A-","B+","B-",
    "AB+","AB-","O+","O-"
]

cities = [
    "Hyderabad",
    "Bengaluru",
    "Chennai",
    "Mumbai",
    "Delhi",
    "Pune",
    "Vijayawada",
    "Visakhapatnam"
]

state_map = {
    "Hyderabad":"Telangana",
    "Bengaluru":"Karnataka",
    "Chennai":"Tamil Nadu",
    "Mumbai":"Maharashtra",
    "Delhi":"Delhi",
    "Pune":"Maharashtra",
    "Vijayawada":"Andhra Pradesh",
    "Visakhapatnam":"Andhra Pradesh"
}

insurance_companies = [
    "Star Health",
    "Apollo Munich",
    "ICICI Lombard",
    "HDFC ERGO",
    "Niva Bupa",
    "Care Health"
]

In [20]:
patients = []

for i in range(1, NUM_PATIENTS + 1):

    gender = random.choice(["Male","Female"])

    if gender == "Male":
        first = fake.first_name_male()
    else:
        first = fake.first_name_female()

    last = fake.last_name()

    dob = fake.date_of_birth(
        minimum_age=18,
        maximum_age=90
    )

    city = random.choice(cities)

    insured = random.choice(["Yes","No"])

    provider = (
        random.choice(insurance_companies)
        if insured == "Yes"
        else "None"
    )

    patients.append({

        "Patient_ID": f"P{i:05}",

        "First_Name": first,

        "Last_Name": last,

        "Gender": gender,

        "DOB": dob,

        "Blood_Group": random.choice(blood_groups),

        "City": city,

        "State": state_map[city],

        "Phone": fake.phone_number(),

        "Insurance": insured,

        "Insurance_Provider": provider

    })

In [21]:
df_patients = pd.DataFrame(patients)

df_patients.head()

,Patient_ID,First_Name,Last_Name,Gender,DOB,Blood_Group,City,State,Phone,Insurance,Insurance_Provider
0,P00001,Faraj,Garg,Male,1981-06-14,O+,Mumbai,Maharashtra,0010943969,Yes,ICICI Lombard
1,P00002,Alexander,Tank,Male,1974-12-04,O+,Mumbai,Maharashtra,4736471027,Yes,Apollo Munich
2,P00003,Sarthak,Sule,Male,1998-09-17,O+,Chennai,Tamil Nadu,+915925556258,No,None
3,P00004,Chatresh,Nagar,Male,1968-05-26,A-,Delhi,Delhi,01473210469,Yes,Care Health
4,P00005,Ubika,Kothari,Female,1957-03-27,B-,Hyderabad,Telangana,09532787747,No,None

In [22]:
print(df_patients.shape)

(5000, 11)

In [23]:
df_patients.to_csv(
    "data/patients.csv",
    index=False
)

In [24]:
dept_map = (
    df_departments
    .set_index("Department_Name")["Department_ID"]
    .to_dict()
)

dept_map

{'Cardiology': 101,
 'Neurology': 102,
 'Orthopedics': 103,
 'Emergency': 104,
 'General Medicine': 105,
 'Surgery': 106,
 'Oncology': 107}

In [27]:
diagnosis_rules = {
    "Heart Disease": {
        "Department": "Cardiology",
        "Stay": (5, 12),
        "Ward": ["ICU", "Private"]
    },

    "Hypertension": {
        "Department": "Cardiology",
        "Stay": (2, 5),
        "Ward": ["General", "Private"]
    },

    "Stroke": {
        "Department": "Neurology",
        "Stay": (7, 15),
        "Ward": ["ICU", "Private"]
    },

    "Migraine": {
        "Department": "Neurology",
        "Stay": (1, 3),
        "Ward": ["General"]
    },

    "Fracture": {
        "Department": "Orthopedics",
        "Stay": (5, 12),
        "Ward": ["Semi-Private", "Private"]
    },

    "Appendicitis": {
        "Department": "Surgery",
        "Stay": (3, 7),
        "Ward": ["General", "Private"]
    },

    "Cancer": {
        "Department": "Oncology",
        "Stay": (10, 30),
        "Ward": ["Private"]
    },

    "Pneumonia": {
        "Department": "General Medicine",
        "Stay": (4, 8),
        "Ward": ["General", "Semi-Private"]
    },

    "Asthma": {
        "Department": "General Medicine",
        "Stay": (2, 5),
        "Ward": ["General"]
    },

    "Diabetes": {
        "Department": "General Medicine",
        "Stay": (2, 4),
        "Ward": ["General"]
    },

    "Kidney Stone": {
        "Department": "General Medicine",
        "Stay": (3, 6),
        "Ward": ["Semi-Private", "Private"]
    },

    "COVID-19": {
        "Department": "Emergency",
        "Stay": (5, 10),
        "Ward": ["ICU", "General"]
    }
}

In [28]:
len(diagnosis_rules)

12

In [29]:
import random
from datetime import timedelta

admissions = []

for i in range(1, 10001):

    # Select random patient
    patient = df_patients.sample(1).iloc[0]

    # Select diagnosis
    diagnosis = random.choice(list(diagnosis_rules.keys()))
    rule = diagnosis_rules[diagnosis]

    # Department
    department_name = rule["Department"]
    department_id = dept_map[department_name]

    # Doctor ONLY from that department
    doctor = df_doctors[
        df_doctors["Department_ID"] == department_id
    ].sample(1).iloc[0]

    # Admission date
    admission_date = fake.date_between(
        start_date="-2y",
        end_date="today"
    )

    # Length of stay
    stay = random.randint(
        rule["Stay"][0],
        rule["Stay"][1]
    )

    discharge_date = admission_date + timedelta(days=stay)

    # Ward
    ward = random.choice(rule["Ward"])

    # Room Number
    if ward == "ICU":
        room = f"ICU-{random.randint(1,20)}"
    elif ward == "Private":
        room = f"P-{random.randint(101,999)}"
    elif ward == "Semi-Private":
        room = f"SP-{random.randint(101,999)}"
    else:
        room = f"G-{random.randint(101,999)}"

    admissions.append({

        "Admission_ID": f"A{i:06d}",
        "Patient_ID": patient["Patient_ID"],
        "Doctor_ID": doctor["Doctor_ID"],
        "Department_ID": department_id,

        "Admission_Date": admission_date,
        "Discharge_Date": discharge_date,

        "Admission_Type": random.choice(
            ["Emergency", "Referral", "Elective"]
        ),

        "Diagnosis": diagnosis,
        "Ward_Type": ward,
        "Room_No": room,
        "Length_of_Stay": stay,
        "Status": "Discharged"

    })

In [30]:
df_admissions = pd.DataFrame(admissions)

df_admissions.head()

,Admission_ID,Patient_ID,Doctor_ID,Department_ID,Admission_Date,Discharge_Date,Admission_Type,Diagnosis,Ward_Type,Room_No,Length_of_Stay,Status
0,A000001,P01079,D0026,102,2026-03-01,2026-03-03,Referral,Migraine,General,G-217,2,Discharged
1,A000002,P00881,D0101,105,2025-12-23,2025-12-29,Emergency,Kidney Stone,Semi-Private,SP-862,6,Discharged
2,A000003,P02567,D0109,105,2025-04-06,2025-04-10,Referral,Diabetes,General,G-994,4,Discharged
3,A000004,P00972,D0088,105,2025-06-25,2025-06-28,Emergency,Diabetes,General,G-995,3,Discharged
4,A000005,P03546,D0030,102,2024-12-25,2024-12-28,Elective,Migraine,General,G-924,3,Discharged

In [31]:
print(df_admissions.shape)

(10000, 12)

In [32]:
df_admissions.to_csv(
    "data/admissions.csv",
    index=False
)

In [33]:
check1 = (
    df_admissions.merge(
        df_doctors[["Doctor_ID", "Department_ID"]],
        on="Doctor_ID",
        suffixes=("_Admission", "_Doctor")
    )
)

wrong_doctors = check1[
    check1["Department_ID_Admission"] != check1["Department_ID_Doctor"]
]

print(wrong_doctors.shape)

(0, 13)

In [34]:
expected_department = {
    "Heart Disease": 101,
    "Hypertension": 101,

    "Stroke": 102,
    "Migraine": 102,

    "Fracture": 103,

    "COVID-19": 104,

    "Pneumonia": 105,
    "Asthma": 105,
    "Diabetes": 105,
    "Kidney Stone": 105,

    "Appendicitis": 106,

    "Cancer": 107
}

check2 = df_admissions.copy()

check2["Expected_Department"] = (
    check2["Diagnosis"]
    .map(expected_department)
)

wrong_department = check2[
    check2["Department_ID"] != check2["Expected_Department"]
]

print(wrong_department.shape)

(0, 13)

In [35]:
expected_wards = {
    "Heart Disease": ["ICU", "Private"],
    "Hypertension": ["General", "Private"],
    "Stroke": ["ICU", "Private"],
    "Migraine": ["General"],
    "Fracture": ["Semi-Private", "Private"],
    "Appendicitis": ["General", "Private"],
    "Cancer": ["Private"],
    "Pneumonia": ["General", "Semi-Private"],
    "Asthma": ["General"],
    "Diabetes": ["General"],
    "Kidney Stone": ["Semi-Private", "Private"],
    "COVID-19": ["ICU", "General"]
}

wrong_ward = df_admissions[
    ~df_admissions.apply(
        lambda row: row["Ward_Type"] in expected_wards[row["Diagnosis"]],
        axis=1
    )
]

print(wrong_ward.shape)

(0, 12)

In [36]:
import random
import pandas as pd

In [37]:
billing = []

for _, row in df_admissions.iterrows():

    consultation = random.randint(500, 2000)

    room_charge = row["Length_of_Stay"] * random.randint(2000, 6000)

    medicine = random.randint(1000, 15000)

    lab = random.randint(500, 10000)

    other = random.randint(0, 5000)

    total = (
        consultation
        + room_charge
        + medicine
        + lab
        + other
    )

    insurance = random.choice(["Yes", "No"])

    if insurance == "Yes":
        insurance_amount = round(total * random.uniform(0.5, 0.9), 2)
    else:
        insurance_amount = 0

    patient_pay = round(total - insurance_amount, 2)

    billing.append({

        "Bill_ID": f"B{len(billing)+1:06d}",

        "Admission_ID": row["Admission_ID"],

        "Consultation_Fee": consultation,

        "Room_Charges": room_charge,

        "Medicine_Cost": medicine,

        "Lab_Cost": lab,

        "Other_Charges": other,

        "Total_Amount": total,

        "Insurance_Covered": insurance_amount,

        "Patient_Payable": patient_pay,

        "Payment_Status": random.choice([
            "Paid",
            "Pending",
            "Partial"
        ])
    })

In [38]:
df_billing = pd.DataFrame(billing)

df_billing.head()

,Bill_ID,Admission_ID,Consultation_Fee,Room_Charges,Medicine_Cost,Lab_Cost,Other_Charges,Total_Amount,Insurance_Covered,Patient_Payable,Payment_Status
0,B000001,A000001,1949,9476,11427,5428,4614,32894,26380.12,6513.88,Paid
1,B000002,A000002,1714,21138,5587,5745,2992,37176,0.00,37176.00,Partial
2,B000003,A000003,677,10988,13360,9122,1726,35873,29913.95,5959.05,Pending
3,B000004,A000004,1927,13008,14982,5167,4781,39865,0.00,39865.00,Pending
4,B000005,A000005,769,8256,14757,8915,1938,34635,25962.94,8672.06,Partial

In [39]:
print(df_billing.shape)

(10000, 11)

In [40]:
df_billing.to_csv(
    "data/billing.csv",
    index=False
)

In [41]:
check3 = df_billing.merge(
    df_admissions[["Admission_ID"]],
    on="Admission_ID",
    how="left",
    indicator=True
)

print(check3[check3["_merge"] != "both"].shape)

(0, 12)

In [42]:
wrong_total = df_billing[
    df_billing["Total_Amount"] != (
        df_billing["Consultation_Fee"]
        + df_billing["Room_Charges"]
        + df_billing["Medicine_Cost"]
        + df_billing["Lab_Cost"]
        + df_billing["Other_Charges"]
    )
]

print(wrong_total.shape)

(0, 11)

In [43]:
wrong_payable = df_billing[
    df_billing["Patient_Payable"] != (
        df_billing["Total_Amount"]
        - df_billing["Insurance_Covered"]
    )
]

print(wrong_payable.shape)

(2550, 11)

In [44]:
wrong_payable = df_billing[
    round(df_billing["Patient_Payable"], 2) !=
    round(
        df_billing["Total_Amount"] -
        df_billing["Insurance_Covered"],
        2
    )
]

print(wrong_payable.shape)

(0, 11)

In [45]:
from faker import Faker
import random

fake = Faker("en_IN")

In [46]:
nurses = []
nurse_number = 1

In [47]:
qualifications = [
    "GNM",
    "B.Sc Nursing",
    "M.Sc Nursing"
]

In [48]:
for _, dept in df_departments.iterrows():

    for i in range(dept["Nurses"]):

        gender = random.choice(["Male", "Female"])

        if gender == "Male":
            first = fake.first_name_male()
        else:
            first = fake.first_name_female()

        last = fake.last_name()

        experience = random.randint(1, 25)

        qualification = random.choice(qualifications)

        salary = random.randint(25000, 80000)

        nurses.append({

            "Nurse_ID": f"N{nurse_number:04d}",

            "Nurse_First_Name": first,

            "Nurse_Last_Name": last,

            "Gender": gender,

            "Department_ID": dept["Department_ID"],

            "Department_Name": dept["Department_Name"],

            "Qualification": qualification,

            "Experience_Years": experience,

            "Salary": salary,

            "Phone": fake.phone_number(),

            "Email": f"{first.lower()}.{last.lower()}@hospital.com"

        })

        nurse_number += 1

In [49]:
df_nurses = pd.DataFrame(nurses)

df_nurses.head()

,Nurse_ID,Nurse_First_Name,Nurse_Last_Name,Gender,Department_ID,Department_Name,Qualification,Experience_Years,Salary,Phone,Email
0,N0001,Wishi,Wason,Female,101,Cardiology,B.Sc Nursing,24,54385,1233160308,wishi.wason@hospital.com
1,N0002,Hiral,Prabhu,Female,101,Cardiology,B.Sc Nursing,12,53448,03114021530,hiral.prabhu@hospital.com
2,N0003,Abhimanyu,Mandal,Male,101,Cardiology,B.Sc Nursing,10,30406,+912761778128,abhimanyu.mandal@hospital.com
3,N0004,Kritika,Korpal,Female,101,Cardiology,B.Sc Nursing,1,61218,+913454223177,kritika.korpal@hospital.com
4,N0005,Yauvani,Choudhary,Female,101,Cardiology,GNM,10,79934,02142765657,yauvani.choudhary@hospital.com

In [50]:
print(df_nurses.shape)

(278, 11)

In [51]:
df_nurses.to_csv(
    "data/nurses.csv",
    index=False
)

In [52]:
check4 = df_nurses.merge(
    df_departments[["Department_ID"]],
    on="Department_ID",
    how="left",
    indicator=True
)

print(check4[check4["_merge"] != "both"].shape)

(0, 12)

In [53]:
dept_lookup = (
    df_departments
    .set_index("Department_ID")["Department_Name"]
    .to_dict()
)

check5 = df_nurses.copy()

check5["Expected_Department"] = (
    check5["Department_ID"]
    .map(dept_lookup)
)

wrong_department = check5[
    check5["Department_Name"] != check5["Expected_Department"]
]

print(wrong_department.shape)

(0, 12)

In [54]:
actual = (
    df_nurses
    .groupby("Department_Name")
    .size()
)

expected = (
    df_departments
    .set_index("Department_Name")["Nurses"]
)

comparison = pd.concat(
    [actual, expected],
    axis=1
)

comparison.columns = [
    "Actual",
    "Expected"
]

comparison

                  Actual  Expected
Department_Name
Cardiology            35        35
Emergency             50        50
General Medicine      70        70
Neurology             28        28
Oncology              20        20
Orthopedics           30        30
Surgery               45        45

In [55]:
master = (
    df_admissions
    .merge(df_patients, on="Patient_ID", how="left")
    .merge(
        df_doctors.drop(columns=["Department_ID", "Department_Name"]),
        on="Doctor_ID",
        how="left"
    )
    .merge(df_departments, on="Department_ID", how="left")
    .merge(df_billing, on="Admission_ID", how="left")
)

master.head()

,Admission_ID,Patient_ID,Doctor_ID,Department_ID,Admission_Date,Discharge_Date,Admission_Type,Diagnosis,Ward_Type,Room_No,...,Bill_ID,Consultation_Fee,Room_Charges,Medicine_Cost,Lab_Cost,Other_Charges,Total_Amount,Insurance_Covered,Patient_Payable,Payment_Status
0,A000001,P01079,D0026,102,2026-03-01,2026-03-03,Referral,Migraine,General,G-217,...,B000001,1949,9476,11427,5428,4614,32894,26380.12,6513.88,Paid
1,A000002,P00881,D0101,105,2025-12-23,2025-12-29,Emergency,Kidney Stone,Semi-Private,SP-862,...,B000002,1714,21138,5587,5745,2992,37176,0.00,37176.00,Partial
2,A000003,P02567,D0109,105,2025-04-06,2025-04-10,Referral,Diabetes,General,G-994,...,B000003,677,10988,13360,9122,1726,35873,29913.95,5959.05,Pending
3,A000004,P00972,D0088,105,2025-06-25,2025-06-28,Emergency,Diabetes,General,G-995,...,B000004,1927,13008,14982,5167,4781,39865,0.00,39865.00,Pending
4,A000005,P03546,D0030,102,2024-12-25,2024-12-28,Elective,Migraine,General,G-924,...,B000005,769,8256,14757,8915,1938,34635,25962.94,8672.06,Partial

In [56]:
master.to_csv(
    "data/Master_Hospital_Dataset.csv",
    index=False
)

print(master.shape)

(10000, 44)

In [57]:
master.isnull().sum()

Admission_ID          0
Patient_ID            0
Doctor_ID             0
Department_ID         0
Admission_Date        0
Discharge_Date        0
Admission_Type        0
Diagnosis             0
Ward_Type             0
Room_No               0
Length_of_Stay        0
Status                0
First_Name            0
Last_Name             0
Gender_x              0
DOB                   0
Blood_Group           0
City                  0
State                 0
Phone_x               0
Insurance             0
Insurance_Provider    0
Doctor_First_Name     0
Doctor_Last_Name      0
Gender_y              0
Qualification         0
Experience_Years      0
Salary                0
Phone_y               0
Email                 0
Department_Name       0
Total_Beds            0
Doctors               0
Nurses                0
Bill_ID               0
Consultation_Fee      0
Room_Charges          0
Medicine_Cost         0
Lab_Cost              0
Other_Charges         0
Total_Amount          0
Insurance_Covered     0
Patient_Payable       0
Payment_Status        0
dtype: int64

In [58]:
master["Admission_ID"].duplicated().sum()

np.int64(0)

In [59]:
master.sample(10, random_state=42)

,Admission_ID,Patient_ID,Doctor_ID,Department_ID,Admission_Date,Discharge_Date,Admission_Type,Diagnosis,Ward_Type,Room_No,...,Bill_ID,Consultation_Fee,Room_Charges,Medicine_Cost,Lab_Cost,Other_Charges,Total_Amount,Insurance_Covered,Patient_Payable,Payment_Status
6252,A006253,P04902,D0014,101,2024-08-06,2024-08-16,Emergency,Heart Disease,Private,P-430,...,B006253,1966,20420,11914,2131,1094,37525,0.00,37525.00,Partial
4684,A004685,P00569,D0063,104,2025-03-28,2025-04-02,Emergency,COVID-19,ICU,ICU-17,...,B004685,798,15950,3731,2611,1433,24523,0.00,24523.00,Paid
1731,A001732,P00655,D0107,105,2024-11-29,2024-12-03,Elective,Kidney Stone,Semi-Private,SP-373,...,B001732,1934,19780,1809,6724,444,30691,0.00,30691.00,Partial
4742,A004743,P01887,D0093,105,2025-12-19,2025-12-25,Elective,Kidney Stone,Semi-Private,SP-195,...,B004743,1178,35478,6748,6846,2642,52892,0.00,52892.00,Pending
4521,A004522,P00489,D0013,101,2025-12-11,2025-12-23,Referral,Heart Disease,ICU,ICU-12,...,B004522,1466,34644,11619,2157,3029,52915,0.00,52915.00,Paid
6340,A006341,P00225,D0029,102,2025-04-12,2025-04-26,Referral,Stroke,Private,P-350,...,B006341,1070,34384,6896,8632,13,50995,0.00,50995.00,Pending
576,A000577,P00737,D0054,104,2024-12-10,2024-12-16,Referral,COVID-19,General,G-355,...,B000577,880,17388,4859,2880,280,26287,0.00,26287.00,Pending
5202,A005203,P00127,D0147,107,2025-05-05,2025-05-24,Emergency,Cancer,Private,P-115,...,B005203,1999,101745,6510,8991,2029,121274,64513.17,56760.83,Partial
6363,A006364,P00216,D0093,105,2026-02-24,2026-02-26,Referral,Diabetes,General,G-661,...,B006364,860,8048,1179,8707,4015,22809,14364.64,8444.36,Partial
439,A000440,P04537,D0027,102,2024-12-15,2024-12-26,Referral,Stroke,Private,P-652,...,B000440,1615,30250,6440,5266,2567,46138,0.00,46138.00,Pending

In [60]:
master = master.rename(columns={
    "Gender_x": "Patient_Gender",
    "Gender_y": "Doctor_Gender",
    "Phone_x": "Patient_Phone",
    "Phone_y": "Doctor_Phone"
})

In [61]:
master.to_csv(
    "data/Hospital_Analytics_Dataset.csv",
    index=False
)

In [62]:
master = master.rename(columns={
    "First_Name": "Patient_First_Name",
    "Last_Name": "Patient_Last_Name"
})

In [63]:
master = master.rename(columns={
    "Gender_x": "Patient_Gender",
    "Gender_y": "Doctor_Gender",
    "Phone_x": "Patient_Phone",
    "Phone_y": "Doctor_Phone",
    "First_Name": "Patient_First_Name",
    "Last_Name": "Patient_Last_Name"
})

In [64]:
master.to_csv(
    "data/Hospital_Analytics_Dataset.csv",
    index=False
)

print("Dataset saved successfully!")
print(master.shape)

Dataset saved successfully!
(10000, 44)

In [65]:
master.columns

Index(['Admission_ID', 'Patient_ID', 'Doctor_ID', 'Department_ID',
       'Admission_Date', 'Discharge_Date', 'Admission_Type', 'Diagnosis',
       'Ward_Type', 'Room_No', 'Length_of_Stay', 'Status',
       'Patient_First_Name', 'Patient_Last_Name', 'Patient_Gender', 'DOB',
       'Blood_Group', 'City', 'State', 'Patient_Phone', 'Insurance',
       'Insurance_Provider', 'Doctor_First_Name', 'Doctor_Last_Name',
       'Doctor_Gender', 'Qualification', 'Experience_Years', 'Salary',
       'Doctor_Phone', 'Email', 'Department_Name', 'Total_Beds', 'Doctors',
       'Nurses', 'Bill_ID', 'Consultation_Fee', 'Room_Charges',
       'Medicine_Cost', 'Lab_Cost', 'Other_Charges', 'Total_Amount',
       'Insurance_Covered', 'Patient_Payable', 'Payment_Status'],
      dtype='object')

In [66]:
master["Insurance_Provider"] = (
    master["Insurance_Provider"]
    .fillna("None")
)

In [67]:
master.to_csv(
    "data/Hospital_Analytics_Dataset.csv",
    index=False
)

In [1]:
import pandas as pd

master = pd.read_csv("data/Hospital_Analytics_Dataset.csv")

In [2]:
print(master.shape)
master.head()

(10000, 44)

,Admission_ID,Patient_ID,Doctor_ID,Department_ID,Admission_Date,Discharge_Date,Admission_Type,Diagnosis,Ward_Type,Room_No,...,Bill_ID,Consultation_Fee,Room_Charges,Medicine_Cost,Lab_Cost,Other_Charges,Total_Amount,Insurance_Covered,Patient_Payable,Payment_Status
0,A000001,P01079,D0026,102,2026-03-01,2026-03-03,Referral,Migraine,General,G-217,...,B000001,1949,9476,11427,5428,4614,32894,26380.12,6513.88,Paid
1,A000002,P00881,D0101,105,2025-12-23,2025-12-29,Emergency,Kidney Stone,Semi-Private,SP-862,...,B000002,1714,21138,5587,5745,2992,37176,0.00,37176.00,Partial
2,A000003,P02567,D0109,105,2025-04-06,2025-04-10,Referral,Diabetes,General,G-994,...,B000003,677,10988,13360,9122,1726,35873,29913.95,5959.05,Pending
3,A000004,P00972,D0088,105,2025-06-25,2025-06-28,Emergency,Diabetes,General,G-995,...,B000004,1927,13008,14982,5167,4781,39865,0.00,39865.00,Pending
4,A000005,P03546,D0030,102,2024-12-25,2024-12-28,Elective,Migraine,General,G-924,...,B000005,769,8256,14757,8915,1938,34635,25962.94,8672.06,Partial

In [3]:
master["Admission_Date"] = pd.to_datetime(master["Admission_Date"])
master["Discharge_Date"] = pd.to_datetime(master["Discharge_Date"])

wrong_dates = master[
    master["Discharge_Date"] < master["Admission_Date"]
]

print("Wrong dates:", wrong_dates.shape)

Wrong dates: (0, 44)

In [4]:
calculated = (
    master["Discharge_Date"] -
    master["Admission_Date"]
).dt.days

wrong_stay = master[
    calculated != master["Length_of_Stay"]
]

print("Wrong stay:", wrong_stay.shape)

Wrong stay: (0, 44)

In [5]:
print(
    "Duplicate Admission IDs:",
    master["Admission_ID"].duplicated().sum()
)

Duplicate Admission IDs: 0

In [6]:
wrong_total = master[
    master["Total_Amount"] != (
        master["Consultation_Fee"] +
        master["Room_Charges"] +
        master["Medicine_Cost"] +
        master["Lab_Cost"] +
        master["Other_Charges"]
    )
]

print("Wrong totals:", wrong_total.shape)

Wrong totals: (0, 44)

In [7]:
wrong_payable = master[
    round(master["Patient_Payable"],2) !=
    round(
        master["Total_Amount"] -
        master["Insurance_Covered"],
        2
    )
]

print("Wrong payable:", wrong_payable.shape)

Wrong payable: (0, 44)

In [10]:
master["Payment_Status"] = "Paid"

In [11]:
master.to_csv(
    "data/Hospital_Analytics_Dataset.csv",
    index=False
)

print("Dataset updated successfully!")

Dataset updated successfully!

In [9]:
import pandas as pd
import numpy as np
import random

master = pd.read_csv("data/Hospital_Analytics_Dataset.csv")

print(master.shape)

(10000, 44)

In [10]:
providers = [
    "Star Health",
    "Niva Bupa",
    "ICICI Lombard",
    "HDFC ERGO",
    "Care Health",
    "New India Assurance",
    "SBI General",
    "Bajaj Allianz"
]

master["Insurance"] = np.where(
    master["Insurance_Covered"] > 0,
    "Yes",
    "No"
)

master["Insurance_Provider"] = master["Insurance_Covered"].apply(
    lambda x: random.choice(providers) if x > 0 else np.nan
)

In [11]:
print(master["Insurance"].value_counts())

Insurance
Yes    5078
No     4922
Name: count, dtype: int64

In [12]:
master.groupby("Insurance")["Insurance_Covered"].describe()

,count,mean,std,min,25%,50%,75%,max
Insurance,,,,,,,,
No,4922.0,0.000000,0.000000,0.00,0.00,0.000,0.0000,0.0
Yes,5078.0,31553.016339,18486.200855,6118.84,19893.02,26802.845,37021.0475,159889.1

In [13]:
master[
    (master["Insurance"] == "No") &
    (master["Insurance_Provider"].notna())
]

Empty DataFrame
Columns: [Admission_ID, Patient_ID, Doctor_ID, Department_ID, Admission_Date, Discharge_Date, Admission_Type, Diagnosis, Ward_Type, Room_No, Length_of_Stay, Status, Patient_First_Name, Patient_Last_Name, Patient_Gender, DOB, Blood_Group, City, State, Patient_Phone, Insurance, Insurance_Provider, Doctor_First_Name, Doctor_Last_Name, Doctor_Gender, Qualification, Experience_Years, Salary, Doctor_Phone, Email, Department_Name, Total_Beds, Doctors, Nurses, Bill_ID, Consultation_Fee, Room_Charges, Medicine_Cost, Lab_Cost, Other_Charges, Total_Amount, Insurance_Covered, Patient_Payable, Payment_Status]
Index: []

[0 rows x 44 columns]

In [14]:
master[
    (master["Insurance"] == "Yes") &
    (master["Insurance_Provider"].isna())
]

Empty DataFrame
Columns: [Admission_ID, Patient_ID, Doctor_ID, Department_ID, Admission_Date, Discharge_Date, Admission_Type, Diagnosis, Ward_Type, Room_No, Length_of_Stay, Status, Patient_First_Name, Patient_Last_Name, Patient_Gender, DOB, Blood_Group, City, State, Patient_Phone, Insurance, Insurance_Provider, Doctor_First_Name, Doctor_Last_Name, Doctor_Gender, Qualification, Experience_Years, Salary, Doctor_Phone, Email, Department_Name, Total_Beds, Doctors, Nurses, Bill_ID, Consultation_Fee, Room_Charges, Medicine_Cost, Lab_Cost, Other_Charges, Total_Amount, Insurance_Covered, Patient_Payable, Payment_Status]
Index: []

[0 rows x 44 columns]

In [15]:
master.to_csv(
    "data/Hospital_Analytics_Dataset.csv",
    index=False
)

print("Hospital_Analytics_Dataset.csv updated successfully!")

Hospital_Analytics_Dataset.csv updated successfully!

In [16]:
check = pd.read_csv("data/Hospital_Analytics_Dataset.csv")

print(check["Insurance"].value_counts())
print(check["Payment_Status"].value_counts())

Insurance
Yes    5078
No     4922
Name: count, dtype: int64
Payment_Status
Paid    10000
Name: count, dtype: int64

In [5]:
import pandas as pd

In [6]:
master = pd.read_csv("data/Hospital_Analytics_Dataset.csv")

print(master.shape)

(10000, 44)

In [7]:
master.columns.tolist()

['Admission_ID',
 'Patient_ID',
 'Doctor_ID',
 'Department_ID',
 'Admission_Date',
 'Discharge_Date',
 'Admission_Type',
 'Diagnosis',
 'Ward_Type',
 'Room_No',
 'Length_of_Stay',
 'Status',
 'Patient_First_Name',
 'Patient_Last_Name',
 'Patient_Gender',
 'DOB',
 'Blood_Group',
 'City',
 'State',
 'Patient_Phone',
 'Insurance',
 'Insurance_Provider',
 'Doctor_First_Name',
 'Doctor_Last_Name',
 'Doctor_Gender',
 'Qualification',
 'Experience_Years',
 'Salary',
 'Doctor_Phone',
 'Email',
 'Department_Name',
 'Total_Beds',
 'Doctors',
 'Nurses',
 'Bill_ID',
 'Consultation_Fee',
 'Room_Charges',
 'Medicine_Cost',
 'Lab_Cost',
 'Other_Charges',
 'Total_Amount',
 'Insurance_Covered',
 'Patient_Payable',
 'Payment_Status']

In [8]:
master = master.drop(columns=[
    "Patient_Phone",
    "Doctor_Phone",
    "Email"
])

print(master.shape)

(10000, 41)

In [9]:
master.to_csv(
    "data/Hospital_Analytics_Dataset.csv",
    index=False
)

print("Final dataset saved successfully!")

Final dataset saved successfully!