In [1]:
import pandas as pd
import numpy as np

In [4]:
import os

In [5]:
os.getcwd()

'C:\\Users\\Tharun'

In [6]:
os.listdir()

['.anaconda',
 '.conda',
 '.continuum',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.packettracer',
 '.vscode',
 'anaconda3',
 'AppData',
 'Application Data',
 'battery-report.html',
 'Cisco Packet Tracer 9.0.0',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'DSA.ipynb',
 'Favorites',
 'Links',
 'Local Settings',
 'Microsoft',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{3cb5bdf5-aaca-11f0-96c1-f6c0e9587a6b}.TM.blf',
 'NTUSER.DAT{3cb5bdf5-aaca-11f0-96c1-f6c0e9587a6b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{3cb5bdf5-aaca-11f0-96c1-f6c0e9587a6b}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'python',
 'pythonp.ipynb',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Videos']

In [7]:
patient=pd.read_csv(r"D:\infosys_Springboard\finalized datasets\patients.csv")

In [9]:
patient.head()

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76

In [10]:
patient.tail()

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
995,PAT-a01bf534,Amber Vang,26,2025-12-02,2025-12-04,emergency,91
996,PAT-87fa07bd,Martha Smith,89,2025-11-18,2025-11-30,emergency,99
997,PAT-8f07e894,Jennifer James,72,2025-12-12,2025-12-21,ICU,69
998,PAT-4ae301e1,Kara Hernandez,47,2025-02-08,2025-02-20,ICU,61
999,PAT-e2ef9c5f,Lorraine Turner,64,2025-05-04,2025-05-08,general_medicine,83

In [12]:
patient.shape

(1000, 7)

In [13]:
patient.columns

Index(['patient_id', 'name', 'age', 'arrival_date', 'departure_date',
       'service', 'satisfaction'],
      dtype='object')

In [14]:
patient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      1000 non-null   object
 1   name            1000 non-null   object
 2   age             1000 non-null   int64
 3   arrival_date    1000 non-null   object
 4   departure_date  1000 non-null   object
 5   service         1000 non-null   object
 6   satisfaction    1000 non-null   int64
dtypes: int64(2), object(5)
memory usage: 54.8+ KB

In [15]:
patient.describe(include="all")

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
count,1000,1000,1000.000000,1000,1000,1000,1000.000000
unique,1000,993,NaN,344,337,4,NaN
top,PAT-09484753,Samantha Robertson,NaN,2025-01-19,2025-09-28,emergency,NaN
freq,1,2,NaN,9,8,263,NaN
mean,NaN,NaN,45.337000,NaN,NaN,NaN,79.597000
std,NaN,NaN,25.999912,NaN,NaN,NaN,11.550325
min,NaN,NaN,0.000000,NaN,NaN,NaN,60.000000
25%,NaN,NaN,23.000000,NaN,NaN,NaN,70.000000
50%,NaN,NaN,46.000000,NaN,NaN,NaN,80.000000
75%,NaN,NaN,68.000000,NaN,NaN,NaN,89.250000
max,NaN,NaN,89.000000,NaN,NaN,NaN,99.000000

In [16]:
patient.isnull().sum()

patient_id        0
name              0
age               0
arrival_date      0
departure_date    0
service           0
satisfaction      0
dtype: int64

In [18]:
missing=(patient.isnull().sum()/len(patient))*100
print(missing)

patient_id        0.0
name              0.0
age               0.0
arrival_date      0.0
departure_date    0.0
service           0.0
satisfaction      0.0
dtype: float64

In [20]:
patient.duplicated().sum()

np.int64(0)

In [21]:
patient.drop_duplicates(inplace=True)

In [22]:
patient.dtypes

patient_id        object
name              object
age                int64
arrival_date      object
departure_date    object
service           object
satisfaction       int64
dtype: object

In [26]:
patient["arrival_date"]=pd.to_datetime(patient["arrival_date"])
patient["departure_date"]=pd.to_datetime(patient["departure_date"])

In [28]:
patient.dtypes

patient_id                object
name                      object
age                        int64
arrival_date      datetime64[ns]
departure_date    datetime64[ns]
service                   object
satisfaction               int64
dtype: object

In [29]:
patient["service"].value_counts()

service
emergency           263
surgery             254
general_medicine    242
ICU                 241
Name: count, dtype: int64

In [30]:
patient["service"]=(patient["service"].str.strip().str.title())

In [31]:
patient["service"].value_counts()

service
Emergency           263
Surgery             254
General_Medicine    242
Icu                 241
Name: count, dtype: int64

In [33]:
patient[patient["age"]<0]

Empty DataFrame
Columns: [patient_id, name, age, arrival_date, departure_date, service, satisfaction]
Index: []

In [34]:
patient[patient["age"]>100]

Empty DataFrame
Columns: [patient_id, name, age, arrival_date, departure_date, service, satisfaction]
Index: []

In [36]:
patient[patient["satisfaction"]<0]

Empty DataFrame
Columns: [patient_id, name, age, arrival_date, departure_date, service, satisfaction]
Index: []

In [37]:
patient[patient["satisfaction"]>100]

Empty DataFrame
Columns: [patient_id, name, age, arrival_date, departure_date, service, satisfaction]
Index: []

In [45]:
patient["length_of_stay"]=(patient["departure_date"]-patient["arrival_date"]).dt.days

In [46]:
patient.head()

,patient_id,name,age,arrival_date,departure_date,service,satisfaction,length_of_stay
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,Surgery,61,6
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,Surgery,83,1
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,General_Medicine,83,6
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,Emergency,81,11
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,Icu,76,7

In [47]:
patient[patient["length_of_stay"]<0]

Empty DataFrame
Columns: [patient_id, name, age, arrival_date, departure_date, service, satisfaction, length_of_stay]
Index: []

In [48]:
patient.columns=(patient.columns.str.strip().str.lower().str.replace(" ","_"))

In [49]:
patient.head()

,patient_id,name,age,arrival_date,departure_date,service,satisfaction,length_of_stay
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,Surgery,61,6
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,Surgery,83,1
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,General_Medicine,83,6
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,Emergency,81,11
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,Icu,76,7

In [50]:
patient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      1000 non-null   object
 1   name            1000 non-null   object
 2   age             1000 non-null   int64
 3   arrival_date    1000 non-null   datetime64[ns]
 4   departure_date  1000 non-null   datetime64[ns]
 5   service         1000 non-null   object
 6   satisfaction    1000 non-null   int64
 7   length_of_stay  1000 non-null   int64
dtypes: datetime64[ns](2), int64(3), object(3)
memory usage: 62.6+ KB

In [51]:
patient.isnull().sum()

patient_id        0
name              0
age               0
arrival_date      0
departure_date    0
service           0
satisfaction      0
length_of_stay    0
dtype: int64

In [53]:
patient.describe()

,age,arrival_date,departure_date,satisfaction,length_of_stay
count,1000.000000,1000,1000,1000.000000,1000.000000
mean,45.337000,2025-07-03 04:29:16.800000256,2025-07-10 14:15:21.600000256,79.597000,7.407000
min,0.000000,2025-01-02 00:00:00,2025-01-06 00:00:00,60.000000,1.000000
25%,23.000000,2025-04-05 18:00:00,2025-04-13 00:00:00,70.000000,4.000000
50%,46.000000,2025-07-07 00:00:00,2025-07-14 00:00:00,80.000000,7.000000
75%,68.000000,2025-09-30 00:00:00,2025-10-09 00:00:00,89.250000,11.000000
max,89.000000,2025-12-31 00:00:00,2026-01-13 00:00:00,99.000000,14.000000
std,25.999912,NaN,NaN,11.550325,3.953857

In [54]:
patient.to_csv("patients_clean.csv",index=False)

In [2]:
import pandas as pd

In [3]:
services=pd.read_csv(r"D:\infosys_Springboard\finalized datasets\services_weekly.csv")

In [4]:
services.head()

,week,month,service,available_beds,patients_request,patients_admitted,patients_refused,patient_satisfaction,staff_morale,event
0,1,1,emergency,32,76,32,44,67,70,none
1,1,1,surgery,45,130,45,85,83,78,flu
2,1,1,general_medicine,37,201,37,164,97,43,flu
3,1,1,ICU,22,31,22,9,84,91,flu
4,2,1,emergency,28,169,28,141,75,64,none

In [5]:
services.tail()

,week,month,service,available_beds,patients_request,patients_admitted,patients_refused,patient_satisfaction,staff_morale,event
203,51,12,ICU,18,15,15,0,87,80,none
204,52,12,emergency,26,130,26,104,88,63,none
205,52,12,surgery,53,39,39,0,82,50,none
206,52,12,general_medicine,65,225,65,160,82,40,flu
207,52,12,ICU,22,24,22,2,80,96,none

In [6]:
services.shape

(208, 10)

In [7]:
services.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   week                  208 non-null    int64
 1   month                 208 non-null    int64
 2   service               208 non-null    object
 3   available_beds        208 non-null    int64
 4   patients_request      208 non-null    int64
 5   patients_admitted     208 non-null    int64
 6   patients_refused      208 non-null    int64
 7   patient_satisfaction  208 non-null    int64
 8   staff_morale          208 non-null    int64
 9   event                 208 non-null    object
dtypes: int64(8), object(2)
memory usage: 16.4+ KB

services.describe()

In [24]:
services.describe(include="all")

,week,month,service,available_beds,patients_request,patients_admitted,patients_refused,patient_satisfaction,staff_morale,event
count,208.000000,208.000000,208,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208
unique,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,4
top,NaN,NaN,emergency,NaN,NaN,NaN,NaN,NaN,NaN,none
freq,NaN,NaN,52,NaN,NaN,NaN,NaN,NaN,NaN,164
mean,26.500000,6.923077,NaN,30.346154,64.870192,28.129808,36.740385,80.000000,72.567308,NaN
std,15.044539,3.634755,NaN,15.172929,58.738572,14.676791,55.015763,11.125546,15.457759,NaN
min,1.000000,1.000000,NaN,8.000000,5.000000,5.000000,0.000000,60.000000,31.000000,NaN
25%,13.750000,4.000000,NaN,18.000000,23.750000,16.000000,0.000000,70.000000,60.000000,NaN
50%,26.500000,7.000000,NaN,27.500000,49.000000,26.000000,13.500000,81.000000,73.000000,NaN
75%,39.250000,10.000000,NaN,40.000000,86.000000,37.000000,52.500000,89.000000,86.000000,NaN
max,52.000000,12.000000,NaN,74.000000,388.000000,74.000000,363.000000,99.000000,99.000000,NaN

In [10]:
services.columns

Index(['week', 'month', 'service', 'available_beds', 'patients_request',
       'patients_admitted', 'patients_refused', 'patient_satisfaction',
       'staff_morale', 'event'],
      dtype='object')

In [11]:
services.isnull().sum()

week                    0
month                   0
service                 0
available_beds          0
patients_request        0
patients_admitted       0
patients_refused        0
patient_satisfaction    0
staff_morale            0
event                   0
dtype: int64

In [12]:
services.duplicated().sum()

np.int64(0)

In [13]:
services.drop_duplicates(inplace=True)

In [14]:
services.dtypes

week                     int64
month                    int64
service                 object
available_beds           int64
patients_request         int64
patients_admitted        int64
patients_refused         int64
patient_satisfaction     int64
staff_morale             int64
event                   object
dtype: object

In [22]:
services["service"].value_counts()

service
emergency           52
surgery             52
general_medicine    52
ICU                 52
Name: count, dtype: int64

In [20]:
services["week"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52])

In [25]:
services[services["available_beds"]<0]

Empty DataFrame
Columns: [week, month, service, available_beds, patients_request, patients_admitted, patients_refused, patient_satisfaction, staff_morale, event]
Index: []

In [27]:
services[services["week"]<0]

Empty DataFrame
Columns: [week, month, service, available_beds, patients_request, patients_admitted, patients_refused, patient_satisfaction, staff_morale, event]
Index: []

In [38]:
services[
    (services["patient_satisfaction"] < 1) |
    (services["patient_satisfaction"] > 5)
]

,week,month,service,available_beds,patients_request,patients_admitted,patients_refused,patient_satisfaction,staff_morale,event
0,1,1,emergency,32,76,32,44,67,70,none
1,1,1,surgery,45,130,45,85,83,78,flu
2,1,1,general_medicine,37,201,37,164,97,43,flu
3,1,1,ICU,22,31,22,9,84,91,flu
4,2,1,emergency,28,169,28,141,75,64,none
...,...,...,...,...,...,...,...,...,...,...
203,51,12,ICU,18,15,15,0,87,80,none
204,52,12,emergency,26,130,26,104,88,63,none
205,52,12,surgery,53,39,39,0,82,50,none
206,52,12,general_medicine,65,225,65,160,82,40,flu
207,52,12,ICU,22,24,22,2,80,96,none

In [40]:
services.columns=(
    services.columns.str.strip().str.lower().str.replace(" ","_"))

In [41]:
services["week"]=services["week"].astype(int)

In [42]:
services.dtypes

week                     int64
month                    int64
service                 object
available_beds           int64
patients_request         int64
patients_admitted        int64
patients_refused         int64
patient_satisfaction     int64
staff_morale             int64
event                   object
dtype: object

In [44]:
services.to_csv("services_weekly.csv",index=False)

In [1]:
import pandas as pd

In [3]:
services_weekly=pd.read_csv(r"D:\infosys_Springboard\finalized datasets\services_weekly.csv")

In [4]:
patients=pd.read_csv(r"D:\infosys_Springboard\finalized datasets\patients.csv")

In [5]:
patients.head()

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76

In [7]:
patients["arrival_date"] = pd.to_datetime(patients["arrival_date"])
patients["departure_date"] = pd.to_datetime(patients["departure_date"])

In [8]:
patients["week"] = patients["arrival_date"].dt.isocalendar().week.astype(int)

In [9]:
patients.columns

Index(['patient_id', 'name', 'age', 'arrival_date', 'departure_date',
       'service', 'satisfaction', 'week'],
      dtype='object')

In [11]:
patients["length_of_stay"] = (
    patients["departure_date"] - patients["arrival_date"]
).dt.days

In [12]:
patient_summary = (
    patients
    .groupby(["week", "service"])
    .agg(
        patient_count=("patient_id", "count"),
        average_length_of_stay=("length_of_stay", "mean"),
        average_satisfaction=("satisfaction", "mean")
    )
    .reset_index()
)

In [13]:
integrated = pd.merge(
    services_weekly,
    patient_summary,
    on=["week", "service"],
    how="left"
)

In [15]:
staff_schedule=pd.read_csv(r"D:\infosys_Springboard\finalized datasets\staff_schedule.csv")

In [16]:
staff_summary = (
    staff_schedule
    .groupby(["week", "service"])
    .agg(
        staff_present=("present", "sum")
    )
    .reset_index()
)

In [17]:
staff_schedule.head()

   week      staff_id    staff_name    role    service  present
0     1  STF-b77cdc60  Allison Hill  doctor  emergency        1
1     2  STF-b77cdc60  Allison Hill  doctor  emergency        1
2     3  STF-b77cdc60  Allison Hill  doctor  emergency        0
3     4  STF-b77cdc60  Allison Hill  doctor  emergency        1
4     5  STF-b77cdc60  Allison Hill  doctor  emergency        1

In [18]:
integrated = integrated.merge(
    staff_summary,
    on=["week", "service"],
    how="left"
)

In [19]:
staff=pd.read_csv(r"D:\infosys_Springboard\finalized datasets\staff.csv")

In [20]:
staff_master = (
    staff
    .groupby("service")
    .agg(
        total_staff=("staff_id", "count")
    )
    .reset_index()
)

In [21]:
integrated = integrated.merge(
    staff_master,
    on="service",
    how="left"
)

In [22]:
integrated.to_csv(
    "hospital_integrated_dataset.csv",
    index=False
)

In [1]:
import pandas as pd

In [2]:
staff=pd.read_csv(r"D:\infosys_Springboard\finalized datasets\staff.csv")

In [3]:
staff.head()

       staff_id       staff_name    role    service
0  STF-5ca26577     Allison Hill  doctor  emergency
1  STF-02ae59ca      Noah Rhodes  doctor  emergency
2  STF-d8006e7c  Angie Henderson  doctor  emergency
3  STF-212d8b31    Daniel Wagner  doctor  emergency
4  STF-107a58e4  Cristian Santos  doctor  emergency

In [4]:
staff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   staff_id    110 non-null    object
 1   staff_name  110 non-null    object
 2   role        110 non-null    object
 3   service     110 non-null    object
dtypes: object(4)
memory usage: 3.6+ KB

In [5]:
staff.describe(include="all")

            staff_id    staff_name   role service
count            110           110    110     110
unique           110           110      3       4
top     STF-5ca26577  Allison Hill  nurse     ICU
freq               1             1     69      32

In [6]:
staff.shape

(110, 4)

In [7]:
staff.columns

Index(['staff_id', 'staff_name', 'role', 'service'], dtype='object')

In [8]:
staff.isnull().sum()

staff_id      0
staff_name    0
role          0
service       0
dtype: int64

In [9]:
staff.duplicated().sum()

np.int64(0)

In [11]:
staff.dtypes

staff_id      object
staff_name    object
role          object
service       object
dtype: object

In [13]:
for col in staff.select_dtypes(include="object"):
    staff[col] = staff[col].str.strip()

In [14]:
staff["service"].value_counts()

service
ICU                 32
emergency           29
general_medicine    27
surgery             22
Name: count, dtype: int64

In [15]:
staff["role"].value_counts()

role
nurse                69
nursing_assistant    23
doctor               18
Name: count, dtype: int64

In [17]:
staff.columns=( staff.columns
                .str.strip()
                .str.lower()
                .str.replace(" ","_")
              )

In [18]:
staff.columns

Index(['staff_id', 'staff_name', 'role', 'service'], dtype='object')

In [19]:
staff.to_csv("staff_clean.csv", index=False)

In [20]:
staff_schedule=pd.read_csv(r"D:\infosys_Springboard\finalized datasets\staff_schedule.csv")

In [21]:
staff_schedule.head()

   week      staff_id    staff_name    role    service  present
0     1  STF-b77cdc60  Allison Hill  doctor  emergency        1
1     2  STF-b77cdc60  Allison Hill  doctor  emergency        1
2     3  STF-b77cdc60  Allison Hill  doctor  emergency        0
3     4  STF-b77cdc60  Allison Hill  doctor  emergency        1
4     5  STF-b77cdc60  Allison Hill  doctor  emergency        1

In [22]:
staff_schedule.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6552 entries, 0 to 6551
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   week        6552 non-null   int64
 1   staff_id    6552 non-null   object
 2   staff_name  6552 non-null   object
 3   role        6552 non-null   object
 4   service     6552 non-null   object
 5   present     6552 non-null   int64
dtypes: int64(2), object(4)
memory usage: 307.3+ KB

In [23]:
staff_schedule.describe(include="all")

               week      staff_id    staff_name   role    service      present
count   6552.000000          6552          6552   6552       6552  6552.000000
unique          NaN           126           126      3          4          NaN
top             NaN  STF-b77cdc60  Allison Hill  nurse  emergency          NaN
freq            NaN            52            52   3796       2028          NaN
mean      26.500000           NaN           NaN    NaN        NaN     0.599817
std       15.009476           NaN           NaN    NaN        NaN     0.489973
min        1.000000           NaN           NaN    NaN        NaN     0.000000
25%       13.750000           NaN           NaN    NaN        NaN     0.000000
50%       26.500000           NaN           NaN    NaN        NaN     1.000000
75%       39.250000           NaN           NaN    NaN        NaN     1.000000
max       52.000000           NaN           NaN    NaN        NaN     1.000000

In [24]:
staff_schedule.shape

(6552, 6)

In [25]:
staff_schedule.columns

Index(['week', 'staff_id', 'staff_name', 'role', 'service', 'present'], dtype='object')

In [26]:
staff_schedule.dtypes

week           int64
staff_id      object
staff_name    object
role          object
service       object
present        int64
dtype: object

In [27]:
staff_schedule.isnull().sum()

week          0
staff_id      0
staff_name    0
role          0
service       0
present       0
dtype: int64

In [28]:
staff_schedule.duplicated().sum()

np.int64(0)

In [29]:
for col in staff_schedule.select_dtypes(include="object"):
    staff_schedule[col] = staff_schedule[col].str.strip()

In [33]:
staff_schedule["service"].value_counts()

service
emergency           2028
ICU                 1768
general_medicine    1456
surgery             1300
Name: count, dtype: int64

In [34]:
staff_schedule["role"].value_counts()

role
nurse                3796
nursing_assistant    1612
doctor               1144
Name: count, dtype: int64

In [35]:
staff_schedule["present"].value_counts()

present
1    3930
0    2622
Name: count, dtype: int64

In [36]:
staff_schedule.columns=( staff_schedule.columns
                         .str.strip()
                         .str.lower()
                         .str.replace(" ","_")
                       )

In [37]:
staff_schedule.columns

Index(['week', 'staff_id', 'staff_name', 'role', 'service', 'present'], dtype='object')

In [39]:
staff_schedule.to_csv("staff_schedule_clean.csv", index=False)