In [1]:
import pandas as pd
import numpy as np

In [2]:
patients = pd.read_csv("diabetic_data.csv")
mapping = pd.read_csv("IDS_mapping.csv")
hospital = pd.read_csv("HospInfo.csv")
provider = pd.read_csv("pos2011.csv")

C:\Users\smile\AppData\Local\Temp\ipykernel_20504\4029040778.py:4: DtypeWarning: Columns (7,8,13,15,16,17,23,29,34,35,43,47,48,58,59,60,61,62,80,81,112,118,119,120,122,130,134,138,173,203,204,205,209,210,225,226,228,229,230,283,338,339,342,344,346,347,349,351,353,354,356,358,360,362,363,365,366,369,371,373,380,382,383,385,386,389,391,393,394,397,401,403,405,407,409,410,412,416,417,419,425,426,427,428,431,432,435,439,441,442,444,446,448,485,494,497) have mixed types. Specify dtype option on import or set low_memory=False.
  provider = pd.read_csv("pos2011.csv")

In [3]:
patients.head()
patients.info()

mapping.head()
mapping.info()

hospital.head()
hospital.info()

provider.head()
provider.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    101766 non-null  object
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  object
 19  diag_2                    101766 non-null  object
 20  diag_3                    101766 non-null  object
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    object
 23  A1Cresult                 17018 non-null   object
 24  metformin                 101766 non-null  object
 25  repaglinide               101766 non-null  object
 26  nateglinide               101766 non-null  object
 27  chlorpropamide            101766 non-null  object
 28  glimepiride               101766 non-null  object
 29  acetohexamide             101766 non-null  object
 30  glipizide                 101766 non-null  object
 31  glyburide                 101766 non-null  object
 32  tolbutamide               101766 non-null  object
 33  pioglitazone              101766 non-null  object
 34  rosiglitazone             101766 non-null  object
 35  acarbose                  101766 non-null  object
 36  miglitol                  101766 non-null  object
 37  troglitazone              101766 non-null  object
 38  tolazamide                101766 non-null  object
 39  examide                   101766 non-null  object
 40  citoglipton               101766 non-null  object
 41  insulin                   101766 non-null  object
 42  glyburide-metformin       101766 non-null  object
 43  glipizide-metformin       101766 non-null  object
 44  glimepiride-pioglitazone  101766 non-null  object
 45  metformin-rosiglitazone   101766 non-null  object
 46  metformin-pioglitazone    101766 non-null  object
 47  change                    101766 non-null  object
 48  diabetesMed               101766 non-null  object
 49  readmitted                101766 non-null  object
dtypes: int64(13), object(37)
memory usage: 38.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   admission_type_id  65 non-null     object
 1   description        62 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4812 entries, 0 to 4811
Data columns (total 29 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   Provider ID                                                    4812 non-null   int64
 1   Hospital Name                                                  4812 non-null   object
 2   Address                                                        4812 non-null   object
 3   City                                                           4812 non-null   object
 4   State                                                          4812 non-null   object
 5   ZIP Code                                                       4812 non-null   int64
 6   County Name                                                    4797 non-null   object
 7   Phone Number                                                   4812 non-null   int64
 8   Hospital Type                                                  4812 non-null   object
 9   Hospital Ownership                                             4812 non-null   object
 10  Emergency Services                                             4812 non-null   bool
 11  Meets criteria for meaningful use of EHRs                      4668 non-null   object
 12  Hospital overall rating                                        4812 non-null   object
 13  Hospital overall rating footnote                               1398 non-null   object
 14  Mortality national comparison                                  4812 non-null   object
 15  Mortality national comparison footnote                         1352 non-null   object
 16  Safety of care national comparison                             4812 non-null   object
 17  Safety of care national comparison footnote                    2168 non-null   object
 18  Readmission national comparison                                4812 non-null   object
 19  Readmission national comparison footnote                       1017 non-null   object
 20  Patient experience national comparison                         4812 non-null   object
 21  Patient experience national comparison footnote                1369 non-null   object
 22  Effectiveness of care national comparison                      4812 non-null   object
 23  Effectiveness of care national comparison footnote             1202 non-null   object
 24  Timeliness of care national comparison                         4812 non-null   object
 25  Timeliness of care national comparison footnote                1266 non-null   object
 26  Efficient use of medical imaging national comparison           4812 non-null   object
 27  Efficient use of medical imaging national comparison footnote  2033 non-null   object
 28  Location                                                       4812 non-null   object
dtypes: bool(1), int64(3), object(25)
memory usage: 1.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138586 entries, 0 to 138585
Columns: 503 entries, PRVDR_CTGRY_SBTYP_CD to PSYCH_UNIT_TRMNN_DT
dtypes: float64(278), int64(4), object(221)
memory usage: 531.8+ MB

In [4]:
print("Patients :", patients.shape)
print("Mapping :", mapping.shape)
print("Hospital :", hospital.shape)
print("Provider :", provider.shape)

Patients : (101766, 50)
Mapping : (67, 2)
Hospital : (4812, 29)
Provider : (138586, 503)

In [5]:
patients.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [6]:
mapping.head()

  admission_type_id    description
0                 1      Emergency
1                 2         Urgent
2                 3       Elective
3                 4        Newborn
4                 5  Not Available

In [7]:
hospital.head()

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote,Location
0,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Acute Care Hospitals,Government - Hospital District or Authority,...,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Below the national average,NaN,"2505 U S HIGHWAY 431 NORTH\nBOAZ, AL\n"
1,10012,DEKALB REGIONAL MEDICAL CENTER,200 MED CENTER DRIVE,FORT PAYNE,AL,35968,DE KALB,2568453150,Acute Care Hospitals,Proprietary,...,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN,"200 MED CENTER DRIVE\nFORT PAYNE, AL\n"
2,10032,WEDOWEE HOSPITAL,209 NORTH MAIN STREET,WEDOWEE,AL,36278,RANDOLPH,2563572111,Acute Care Hospitals,Government - Hospital District or Authority,...,NaN,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,"209 NORTH MAIN STREET\nWEDOWEE, AL\n"
3,10095,HALE COUNTY HOSPITAL,508 GREEN STREET,GREENSBORO,AL,36744,HALE,3346243024,Acute Care Hospitals,Government - Local,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Below the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,"508 GREEN STREET\nGREENSBORO, AL\n"
4,10131,CRESTWOOD MEDICAL CENTER,ONE HOSPITAL DR SE,HUNTSVILLE,AL,35801,MADISON,2568823100,Acute Care Hospitals,Proprietary,...,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,"ONE HOSPITAL DR SE\nHUNTSVILLE, AL\n"

In [8]:
provider.head()

,PRVDR_CTGRY_SBTYP_CD,PRVDR_CTGRY_CD,CHOW_CNT,CHOW_DT,CITY_NAME,ACPTBL_POC_SW,CMPLNC_STUS_CD,SSA_CNTY_CD,CROSS_REF_PROVIDER_NUMBER,CRTFCTN_DT,...,THRPTC_RCRTNL_PRTM_CNT,FED_PGM_NAME,EMPLEE_CNT,GNRL_FAC_TYPE_CD,NPP_TYPE_CD,VLNTR_OTHR_CNT,VLNTR_CNT,cross_rfrnc_prvdr_num,rltd_prvdr_num,PSYCH_UNIT_TRMNN_DT
0,1.0,1,1.0,NaN,DOTHAN,N,A,340.0,010163,6/8/2000,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1,0.0,NaN,BRIDGEPORT,N,A,350.0,NaN,3/16/2001,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,1,0.0,NaN,BOAZ,Y,A,470.0,NaN,10/3/2002,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,1,1.0,7/1/2010,FLORENCE,N,B,380.0,NaN,7/15/2010,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,1,0.0,NaN,OPP,N,B,190.0,NaN,8/13/2009,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
patients.columns
mapping.columns
hospital.columns
provider.columns

Index(['PRVDR_CTGRY_SBTYP_CD', 'PRVDR_CTGRY_CD', 'CHOW_CNT', 'CHOW_DT',
       'CITY_NAME', 'ACPTBL_POC_SW', 'CMPLNC_STUS_CD', 'SSA_CNTY_CD',
       'CROSS_REF_PROVIDER_NUMBER', 'CRTFCTN_DT',
       ...
       'THRPTC_RCRTNL_PRTM_CNT', 'FED_PGM_NAME', 'EMPLEE_CNT',
       'GNRL_FAC_TYPE_CD', 'NPP_TYPE_CD', 'VLNTR_OTHR_CNT', 'VLNTR_CNT',
       'cross_rfrnc_prvdr_num', 'rltd_prvdr_num', 'PSYCH_UNIT_TRMNN_DT'],
      dtype='object', length=503)

In [10]:
mapping.info()

hospital.info()
patients.info()
provider.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   admission_type_id  65 non-null     object
 1   description        62 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4812 entries, 0 to 4811
Data columns (total 29 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   Provider ID                                                    4812 non-null   int64
 1   Hospital Name                                                  4812 non-null   object
 2   Address                                                        4812 non-null   object
 3   City                                                           4812 non-null   object
 4   State                                                          4812 non-null   object
 5   ZIP Code                                                       4812 non-null   int64
 6   County Name                                                    4797 non-null   object
 7   Phone Number                                                   4812 non-null   int64
 8   Hospital Type                                                  4812 non-null   object
 9   Hospital Ownership                                             4812 non-null   object
 10  Emergency Services                                             4812 non-null   bool
 11  Meets criteria for meaningful use of EHRs                      4668 non-null   object
 12  Hospital overall rating                                        4812 non-null   object
 13  Hospital overall rating footnote                               1398 non-null   object
 14  Mortality national comparison                                  4812 non-null   object
 15  Mortality national comparison footnote                         1352 non-null   object
 16  Safety of care national comparison                             4812 non-null   object
 17  Safety of care national comparison footnote                    2168 non-null   object
 18  Readmission national comparison                                4812 non-null   object
 19  Readmission national comparison footnote                       1017 non-null   object
 20  Patient experience national comparison                         4812 non-null   object
 21  Patient experience national comparison footnote                1369 non-null   object
 22  Effectiveness of care national comparison                      4812 non-null   object
 23  Effectiveness of care national comparison footnote             1202 non-null   object
 24  Timeliness of care national comparison                         4812 non-null   object
 25  Timeliness of care national comparison footnote                1266 non-null   object
 26  Efficient use of medical imaging national comparison           4812 non-null   object
 27  Efficient use of medical imaging national comparison footnote  2033 non-null   object
 28  Location                                                       4812 non-null   object
dtypes: bool(1), int64(3), object(25)
memory usage: 1.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    101766 non-null  object
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  object
 19  diag_2                    101766 non-null  object
 20  diag_3                    101766 non-null  object
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    object
 23  A1Cresult                 17018 non-null   object
 24  metformin                 101766 non-null  object
 25  repaglinide               101766 non-null  object
 26  nateglinide               101766 non-null  object
 27  chlorpropamide            101766 non-null  object
 28  glimepiride               101766 non-null  object
 29  acetohexamide             101766 non-null  object
 30  glipizide                 101766 non-null  object
 31  glyburide                 101766 non-null  object
 32  tolbutamide               101766 non-null  object
 33  pioglitazone              101766 non-null  object
 34  rosiglitazone             101766 non-null  object
 35  acarbose                  101766 non-null  object
 36  miglitol                  101766 non-null  object
 37  troglitazone              101766 non-null  object
 38  tolazamide                101766 non-null  object
 39  examide                   101766 non-null  object
 40  citoglipton               101766 non-null  object
 41  insulin                   101766 non-null  object
 42  glyburide-metformin       101766 non-null  object
 43  glipizide-metformin       101766 non-null  object
 44  glimepiride-pioglitazone  101766 non-null  object
 45  metformin-rosiglitazone   101766 non-null  object
 46  metformin-pioglitazone    101766 non-null  object
 47  change                    101766 non-null  object
 48  diabetesMed               101766 non-null  object
 49  readmitted                101766 non-null  object
dtypes: int64(13), object(37)
memory usage: 38.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138586 entries, 0 to 138585
Columns: 503 entries, PRVDR_CTGRY_SBTYP_CD to PSYCH_UNIT_TRMNN_DT
dtypes: float64(278), int64(4), object(221)
memory usage: 531.8+ MB

In [11]:
patients.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [12]:
patients.replace("?", np.nan, inplace=True)

In [13]:
patients.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                         2273
gender                          0
age                             0
weight                      98569
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  40256
medical_specialty           49949
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         21
diag_2                        358
diag_3                       1423
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [14]:
patients = patients.drop_duplicates()

In [15]:
patients.shape

(101766, 50)

In [16]:
patients["gender"].unique()

array(['Female', 'Male', 'Unknown/Invalid'], dtype=object)

In [17]:
patients["race"].unique()

array(['Caucasian', 'AfricanAmerican', nan, 'Other', 'Asian', 'Hispanic'],
      dtype=object)

In [18]:
patients["readmitted"].unique()

array(['NO', '>30', '<30'], dtype=object)

In [19]:
patients["race"] = patients["race"].fillna("Unknown")
patients["gender"] = patients["gender"].fillna("Unknown")

In [20]:
mapping.head(20)

,admission_type_id,description
0,1,Emergency
1,2,Urgent
2,3,Elective
3,4,Newborn
4,5,Not Available
5,6,NaN
6,7,Trauma Center
7,8,Not Mapped
8,NaN,NaN
9,discharge_disposition_id,description
10,1,Discharged to home
11,2,Discharged/transferred to another short term h...
12,3,Discharged/transferred to SNF
13,4,Discharged/transferred to ICF
14,5,Discharged/transferred to another type of inpa...
15,6,Discharged/transferred to home with home healt...
16,7,Left AMA
17,8,Discharged/transferred to home under care of H...
18,9,Admitted as an inpatient to this hospital
19,10,Neonate discharged to another hospital for neo...

In [21]:
hospital.drop_duplicates(inplace=True)

hospital.replace("?", np.nan, inplace=True)

hospital.isnull().sum()

Provider ID                                                         0
Hospital Name                                                       0
Address                                                             0
City                                                                0
State                                                               0
ZIP Code                                                            0
County Name                                                        15
Phone Number                                                        0
Hospital Type                                                       0
Hospital Ownership                                                  0
Emergency Services                                                  0
Meets criteria for meaningful use of EHRs                         144
Hospital overall rating                                             0
Hospital overall rating footnote                                 3414
Mortality national comparison                                       0
Mortality national comparison footnote                           3460
Safety of care national comparison                                  0
Safety of care national comparison footnote                      2644
Readmission national comparison                                     0
Readmission national comparison footnote                         3795
Patient experience national comparison                              0
Patient experience national comparison footnote                  3443
Effectiveness of care national comparison                           0
Effectiveness of care national comparison footnote               3610
Timeliness of care national comparison                              0
Timeliness of care national comparison footnote                  3546
Efficient use of medical imaging national comparison                0
Efficient use of medical imaging national comparison footnote    2779
Location                                                            0
dtype: int64

In [22]:
provider.drop_duplicates(inplace=True)

provider.replace("?", np.nan, inplace=True)

provider.isnull().sum()

PRVDR_CTGRY_SBTYP_CD       1007
PRVDR_CTGRY_CD                0
CHOW_CNT                     59
CHOW_DT                  120514
CITY_NAME                     0
                          ...
VLNTR_OTHR_CNT           133779
VLNTR_CNT                133779
cross_rfrnc_prvdr_num    138586
rltd_prvdr_num           138586
PSYCH_UNIT_TRMNN_DT      138586
Length: 503, dtype: int64

In [23]:
patients = patients.sample(n=2000, random_state=42)

In [24]:
patients.shape

(2000, 50)

In [26]:
patients.to_csv("hospital_cleaned.csv", index=False)

In [27]:
patients.isnull().sum().sort_values(ascending=False)

weight                      1935
max_glu_serum               1902
A1Cresult                   1679
medical_specialty            972
payer_code                   814
diag_3                        30
diag_2                         6
encounter_id                   0
patient_nbr                    0
race                           0
time_in_hospital               0
admission_source_id            0
num_lab_procedures             0
num_procedures                 0
admission_type_id              0
discharge_disposition_id       0
gender                         0
age                            0
number_inpatient               0
number_emergency               0
number_outpatient              0
num_medications                0
number_diagnoses               0
diag_1                         0
metformin                      0
repaglinide                    0
nateglinide                    0
chlorpropamide                 0
glimepiride                    0
acetohexamide                  0
glipizide                      0
glyburide                      0
tolbutamide                    0
pioglitazone                   0
rosiglitazone                  0
acarbose                       0
miglitol                       0
troglitazone                   0
tolazamide                     0
examide                        0
citoglipton                    0
insulin                        0
glyburide-metformin            0
glipizide-metformin            0
glimepiride-pioglitazone       0
metformin-rosiglitazone        0
metformin-pioglitazone         0
change                         0
diabetesMed                    0
readmitted                     0
dtype: int64

In [28]:
patients.duplicated().sum()

np.int64(0)

In [29]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2000 entries, 35956 to 96139
Data columns (total 50 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   encounter_id              2000 non-null   int64
 1   patient_nbr               2000 non-null   int64
 2   race                      2000 non-null   object
 3   gender                    2000 non-null   object
 4   age                       2000 non-null   object
 5   weight                    65 non-null     object
 6   admission_type_id         2000 non-null   int64
 7   discharge_disposition_id  2000 non-null   int64
 8   admission_source_id       2000 non-null   int64
 9   time_in_hospital          2000 non-null   int64
 10  payer_code                1186 non-null   object
 11  medical_specialty         1028 non-null   object
 12  num_lab_procedures        2000 non-null   int64
 13  num_procedures            2000 non-null   int64
 14  num_medications           2000 non-null   int64
 15  number_outpatient         2000 non-null   int64
 16  number_emergency          2000 non-null   int64
 17  number_inpatient          2000 non-null   int64
 18  diag_1                    2000 non-null   object
 19  diag_2                    1994 non-null   object
 20  diag_3                    1970 non-null   object
 21  number_diagnoses          2000 non-null   int64
 22  max_glu_serum             98 non-null     object
 23  A1Cresult                 321 non-null    object
 24  metformin                 2000 non-null   object
 25  repaglinide               2000 non-null   object
 26  nateglinide               2000 non-null   object
 27  chlorpropamide            2000 non-null   object
 28  glimepiride               2000 non-null   object
 29  acetohexamide             2000 non-null   object
 30  glipizide                 2000 non-null   object
 31  glyburide                 2000 non-null   object
 32  tolbutamide               2000 non-null   object
 33  pioglitazone              2000 non-null   object
 34  rosiglitazone             2000 non-null   object
 35  acarbose                  2000 non-null   object
 36  miglitol                  2000 non-null   object
 37  troglitazone              2000 non-null   object
 38  tolazamide                2000 non-null   object
 39  examide                   2000 non-null   object
 40  citoglipton               2000 non-null   object
 41  insulin                   2000 non-null   object
 42  glyburide-metformin       2000 non-null   object
 43  glipizide-metformin       2000 non-null   object
 44  glimepiride-pioglitazone  2000 non-null   object
 45  metformin-rosiglitazone   2000 non-null   object
 46  metformin-pioglitazone    2000 non-null   object
 47  change                    2000 non-null   object
 48  diabetesMed               2000 non-null   object
 49  readmitted                2000 non-null   object
dtypes: int64(13), object(37)
memory usage: 796.9+ KB

In [30]:
patients.describe(include='all')

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
count,2.000000e+03,2.000000e+03,2000,2000,2000,65,2000.000000,2000.000000,2000.000000,2000.00000,...,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000
unique,NaN,NaN,6,3,10,4,NaN,NaN,NaN,NaN,...,1,4,2,1,1,1,1,2,2,3
top,NaN,NaN,Caucasian,Female,[70-80),[75-100),NaN,NaN,NaN,NaN,...,No,No,No,No,No,No,No,No,Yes,NO
freq,NaN,NaN,1467,1114,515,34,NaN,NaN,NaN,NaN,...,2000,933,1988,2000,2000,2000,2000,1098,1539,1058
mean,1.625879e+08,5.325548e+07,NaN,NaN,NaN,NaN,1.996500,3.772500,5.828500,4.36400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1.014672e+08,3.807238e+07,NaN,NaN,NaN,NaN,1.447942,5.227179,4.069689,2.95023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.139226e+06,3.326400e+04,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,8.569056e+07,2.325740e+07,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,2.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1.494386e+08,4.491974e+07,NaN,NaN,NaN,NaN,1.000000,1.000000,7.000000,4.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2.254918e+08,8.629717e+07,NaN,NaN,NaN,NaN,3.000000,5.000000,7.000000,6.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,4.438243e+08,1.895026e+08,NaN,NaN,NaN,NaN,8.000000,25.000000,20.000000,14.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
print("Rows :", patients.shape[0])
print("Columns :", patients.shape[1])

print("Duplicates :", patients.duplicated().sum())

print("Missing Values :", patients.isnull().sum().sum())

Rows : 2000
Columns : 50
Duplicates : 0
Missing Values : 7338

In [32]:
patients.to_csv("hospital_raw_data.csv", index=False)

In [33]:
test = pd.read_csv("hospital_cleaned.csv")

test.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,110939484,19274094,Caucasian,Female,[70-80),NaN,1,1,6,11,...,No,Steady,No,No,No,No,No,No,Yes,NO
1,170328306,65634327,Caucasian,Male,[50-60),NaN,1,1,1,1,...,No,No,No,No,No,No,No,No,Yes,NO
2,245688426,100657359,Caucasian,Female,[60-70),NaN,3,6,1,4,...,No,No,No,No,No,No,No,No,Yes,NO
3,150826224,83144448,Caucasian,Male,[30-40),NaN,2,1,1,12,...,No,No,No,No,No,No,No,No,Yes,>30
4,135993852,65234214,AfricanAmerican,Female,[60-70),NaN,1,2,7,1,...,No,No,No,No,No,No,No,No,Yes,<30

In [34]:
print(patients.columns.tolist())

['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight', 'admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'payer_code', 'medical_specialty', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted']

In [35]:
print(hospital.columns.tolist())

['Provider ID', 'Hospital Name', 'Address', 'City', 'State', 'ZIP Code', 'County Name', 'Phone Number', 'Hospital Type', 'Hospital Ownership', 'Emergency Services', 'Meets criteria for meaningful use of EHRs', 'Hospital overall rating', 'Hospital overall rating footnote', 'Mortality national comparison', 'Mortality national comparison footnote', 'Safety of care national comparison', 'Safety of care national comparison footnote', 'Readmission national comparison', 'Readmission national comparison footnote', 'Patient experience national comparison', 'Patient experience national comparison footnote', 'Effectiveness of care national comparison', 'Effectiveness of care national comparison footnote', 'Timeliness of care national comparison', 'Timeliness of care national comparison footnote', 'Efficient use of medical imaging national comparison', 'Efficient use of medical imaging national comparison footnote', 'Location']

In [36]:
print(provider.columns.tolist())

['PRVDR_CTGRY_SBTYP_CD', 'PRVDR_CTGRY_CD', 'CHOW_CNT', 'CHOW_DT', 'CITY_NAME', 'ACPTBL_POC_SW', 'CMPLNC_STUS_CD', 'SSA_CNTY_CD', 'CROSS_REF_PROVIDER_NUMBER', 'CRTFCTN_DT', 'ELGBLTY_SW', 'FAC_NAME', 'INTRMDRY_CARR_CD', 'MDCD_VNDR_NUM', 'ORGNL_PRTCPTN_DT', 'CHOW_PRIOR_DT', 'INTRMDRY_CARR_PRIOR_CD', 'PRVDR_NUM', 'REC_STUS_CD', 'RGN_CD', 'SKLTN_REC_SW', 'STATE_CD', 'SSA_STATE_CD', 'STATE_RGN_CD', 'ST_ADR', 'PHNE_NUM', 'PGM_TRMNTN_CD', 'TRMNTN_EXPRTN_DT', 'SRVY_PRPSE_CD', 'GNRL_CNTL_TYPE_CD', 'ZIP_CD', 'FIPS_STATE_CD', 'FIPS_CNTY_CD', 'CBSA_URBN_RRL_IND', 'ACRDTN_EFCTV_DT', 'ACRDTN_EXPRTN_DT', 'ACRDTN_TYPE_CD', 'ACTVTY_PROFNL_CNTRCT_CNT', 'ACTVTY_PROFNL_FLTM_CNT', 'ACTVTY_PROFNL_PRTM_CNT', 'ACTVTY_STF_OTHR_CNTRCT_CNT', 'ACTVTY_STF_OTHR_FLTM_CNT', 'ACTVTY_STF_OTHR_PRTM_CNT', 'ACUTE_RESP_CARE_CD', 'PROFNL_ADMIN_CNTRCT_CNT', 'PROFNL_ADMIN_FLTM_CNT', 'PROFNL_ADMIN_PRTM_CNT', 'ADMSN_SUSPNSN_DT', 'ADMSN_SUSPNSN_PRIOR_DT', 'HHA_TRNG_PGM_CD', 'MR_BED_CNT', 'MDCR_SNF_BED_CNT', 'MDCD_SNF_BED_CNT', 'MDCR_MDCD_SNF_BED_CNT', 'CRTFD_BED_CNT', 'BED_CNT', 'BRNCH_OPRTN_SW', 'BRNCH_CNT', 'CLIA_ID_NUMBER_1', 'CLIA_ID_NUMBER_2', 'CLIA_ID_NUMBER_3', 'CLIA_ID_NUMBER_4', 'CLIA_ID_NUMBER_5', 'NRS_AIDE_CNTRCT_CNT', 'NRS_AIDE_FLTM_CNT', 'NRS_AIDE_PRTM_CNT', 'CRNA_CNT', 'CHOW_SW', 'RN_24_HR_WVR_SW', 'RN_7_DAY_WVR_SW', 'BED_PER_ROOM_WVR_SW', 'LSC_WVR_SW', 'ROOM_SIZE_WVR_SW', 'SCOPE_OF_SRVC_WVR_SW', 'TCHNCL_PRSNEL_WVR_SW', 'CNSLR_EMPLEE_CNT', 'CNSLR_VLNTR_CNT', 'SRVY_EVER_ACRDTD_SW', 'SRVY_EVER_NACRDTD_SW', 'SRVY_EVER_SB_SW', 'ASC_BGN_SRVC_DT', 'VLDTN_SRVY_DT', 'DNTST_CNTRCT_CNT', 'DNTST_FLTM_CNT', 'DNTST_PRTM_CNT', 'DIETN_CNT', 'DIETN_CNTRCT_CNT', 'DIETN_FLTM_CNT', 'DIETN_PRTM_CNT', 'DRCT_CARE_PRSNEL_CNT', 'DRCTR_QUALN_CD', 'ESRD_NTWRK_NUM', 'EXPRMT_RSRCH_CNDCTD_SW', 'FQHC_APPROVED_RHC_PROVIDER_NUM', 'FAX_PHNE_NUM', 'FED_PGM_SPRT_SW', 'FED_FUNDD_FQHC_SW', 'FY_END_MO_DAY_CD', 'FOOD_SRVC_CNTRCT_CNT', 'FOOD_SRVC_FLTM_CNT', 'FOOD_SRVC_PRTM_CNT', 'FQHC_APRVD_RHC_SW', 'HHA_QLFYD_OPT_SPCH_SW', 'HH_AIDE_CNT', 'HH_AIDE_VLNTR_CNT', 'HMMKR_EMPLEE_CNT', 'HMMKR_VLNTR_CNT', 'MDCR_HOSPC_SW', 'HOSP_BSD_SW', 'HSEKPNG_CNTRCT_CNT', 'HSEKPNG_FLTM_CNT', 'HSEKPNG_PRTM_CNT', 'LTC_CROSS_REF_PROVIDER_NUMBER', 'LPN_LVN_CNT', 'LPN_LVN_CNTRCT_CNT', 'LPN_LVN_FLTM_CNT', 'LPN_LVN_PRTM_CNT', 'LPN_LVN_VLNTR_CNT', 'AGRMT_BGN_DT', 'AGRMT_END_DT', 'AGRMT_EXTNSN_DT', 'MEDICARE_HOSPICE_PROVIDER_NUM', 'MEDICARE_MEDICAID_PRVDR_NUMBER', 'MDCL_DRCTR_CNTRCT_CNT', 'MDCL_DRCTR_FLTM_CNT', 'MDCL_DRCTR_PRTM_CNT', 'MDCL_SCHL_AFLTN_CD', 'MDCL_SCL_WORKR_CNT', 'MDCL_SCL_WORKR_VLNTR_CNT', 'MDCL_TCHNLGST_CNT', 'MDCD_MDCR_PRTCPTG_PRVDR_SW', 'MDCTN_AIDE_CNTRCT_CNT', 'MDCTN_AIDE_FLTM_CNT', 'MDCTN_AIDE_PRTM_CNT', 'MEET_1861_SW', 'MENTL_HLTH_SRVC_CNTRCT_CNT', 'MENTL_HLTH_SRVC_FLTM_CNT', 'MENTL_HLTH_SRVC_PRTM_CNT', 'MLT_FAC_ORG_NAME', 'MLT_OWND_FAC_ORG_SW', 'NUCLR_MDCN_TCHNCN_CNT', 'SHIFT_4_TUE_PTNT_CNT', 'NAT_CNTRCT_CNT', 'NAT_FLTM_CNT', 'NAT_PRTM_CNT', 'NRS_PRCTNR_CNT', 'NRS_ADMINV_CNTRCT_CNT', 'NRS_ADMINV_FLTM_CNT', 'NRS_ADMINV_PRTM_CNT', 'OCPTNL_THRPST_CNTRCT_CNT', 'OCPTNL_THRPST_FLTM_CNT', 'OCPTNL_THRPST_PRTM_CNT', 'OCPTNL_THRPST_CNT', 'OT_AIDE_CNTRCT_CNT', 'OT_AIDE_FLTM_CNT', 'OT_AIDE_PRTM_CNT', 'OT_ASTNT_AIDE_CNTRCT_CNT', 'OT_ASTNT_AIDE_FLTM_CNT', 'OT_ASTNT_AIDE_PRTM_CNT', 'OPRTG_ROOM_CNT', 'ORGNZ_FMLY_MBR_GRP_SW', 'ORGNZ_RSDNT_GRP_SW', 'ORTHTC_PRSTHTC_SRVC_CD', 'STF_OTHR_CNTRCT_CNT', 'STF_OTHR_FLTM_CNT', 'STF_OTHR_PRTM_CNT', 'PRSNEL_OTHR_CNT', 'PHYSN_OTHR_CNTRCT_CNT', 'PHYSN_OTHR_FLTM_CNT', 'PHYSN_OTHR_PRTM_CNT', 'SCL_SRVC_OTHR_STF_CNTRCT_CNT', 'SCL_SRVC_OTHR_STF_FLTM_CNT', 'SCL_SRVC_OTHR_STF_PRTM_CNT', 'PARENT_PROVIDER_NUMBER', 'MDCR_PRTCPTN_OP_PT_SPCH_SW', 'PHRMCST_CNTRCT_CNT', 'PHRMCST_FLTM_CNT', 'PHRMCST_PRTM_CNT', 'PHYS_THRPST_ARNGMT_CNT', 'PHYS_THRPST_CNT', 'PHYS_THRPST_CNTRCT_CNT', 'PHYS_THRPST_FLTM_CNT', 'PHYS_THRPST_PRTM_CNT', 'PHYS_THRPST_STF_CNT', 'PT_AIDE_CNTRCT_CNT', 'PT_AIDE_FLTM_CNT', 'PT_AIDE_PRTM_CNT', 'PT_ASTNT_CNTRCT_CNT', 'PT_ASTNT_FLTM_CNT', 'PT_ASTNT_PRTM_CNT', 'PHYSN_ASTNT_CNT', 'PHYSN_EXT_CNTRCT_CNT', 'PHYSN_EXT_FLTM_CNT', 'PHYSN_EXT_PRTM_CNT', 'PHYSN_EXT_SRVC_OFSITE_RSDNT_SW', 'PHYSN_EXT_SRVC_ONST_NRSDNT_SW', 'PHYSN_EXT_SRVC_ONST_RSDNT_SW', 'PHYSN_CNT', 'RSDNT_PHYSN_CNT', 'PHYSN_VLNTR_CNT', 'PDTRST_CNTRCT_CNT', 'PDTRST_FLTM_CNT', 'PDTRST_PRTM_CNT', 'AGRMT_END_PRIOR_DT', 'AGRMT_EXTNSN_PRIOR_DT', 'RSCND_SUSPNSN_PRIOR_DT', 'PGM_PRTCPTN_CD', 'PRVDR_BSD_FAC_SW', 'PSYCH_UNIT_BED_CNT', 'PSYCH_UNIT_EFCTV_DT', 'PSYCH_UNIT_SW', 'PSYCH_UNIT_TRMNTN_CD', 'PSYCH_UNIT_TRMNTN_DT', 'PSYCHLGST_CNT', 'RDLGY_TCHNCN_CNT', 'OVRRD_BED_CNT_SW', 'OVRRD_STFG_SW', 'OVRRD_NRS_BED_SW', 'RN_CNTRCT_CNT', 'RN_FLTM_CNT', 'RN_PRTM_CNT', 'RN_CNT', 'RN_VLNTR_CNT', 'REG_PHRMCST_CNT', 'REHAB_UNIT_BED_CNT', 'REHAB_UNIT_EFCTV_DT', 'REHAB_UNIT_SW', 'REHAB_UNIT_TRMNTN_CD', 'REHAB_UNIT_TRMNTN_DT', 'RELATED_PROVIDER_NUMBER', 'RSCND_SUSPNSN_DT', 'RSDNT_PGM_ADA_APRVD_SW', 'RSDNT_PGM_AMA_APRVD_SW', 'RSDNT_PGM_AOA_APRVD_SW', 'RSDNT_PGM_OTHR_APRVD_SW', 'INHLTN_THRPST_CNT', 'RN_DRCTR_CNTRCT_CNT', 'RN_DRCTR_FLTM_CNT', 'RN_DRCTR_PRTM_CNT', 'ACTVTY_OFSITE_RSDNT_SW', 'ACTVTY_ONST_NRSDNT_SW', 'ACTVTY_ONST_RSDNT_SW', 'APLNC_EQUIP_SRVC_CD', 'BLOOD_SRVC_OFSITE_RSDNT_SW', 'BLOOD_SRVC_ONST_NRSDNT_SW', 'BLOOD_SRVC_ONST_RSDNT_SW', 'CL_SRVC_OFSITE_RSDNT_SW', 'CL_SRVC_ONST_NRSDNT_SW', 'CL_SRVC_ONST_RSDNT_SW', 'CNSLNG_SRVC_CD', 'DNTL_SRVC_ONST_NRSDNT_SW', 'DNTL_SRVC_OFSITE_RSDNT_SW', 'DNTL_SRVC_ONST_RSDNT_SW', 'DTRY_ONST_NRSDNT_SW', 'DTRY_OFSITE_RSDNT_SW', 'DTRY_ONST_RSDNT_SW', 'EKG_SRVC_CD', 'HH_AIDE_SRVC_CD', 'HMMKR_SRVC_CD', 'HSEKPNG_SRVC_ONST_NRSDNT_SW', 'HSEKPNG_SRVC_OFSITE_RSDNT_SW', 'HSEKPNG_SRVC_ONST_RSDNT_SW', 'INTRN_RSDNT_SRVC_CD', 'LAB_SRVC_CD', 'MDCL_SCL_SRVC_CD', 'MDCL_SUPLY_SRVC_CD', 'MENTL_HLTH_OFSITE_RSDNT_SW', 'MENTL_HLTH_ONST_RSDNT_SW', 'MENTL_HLTH_ONST_NRSDNT_SW', 'NRSNG_SRVC_CD', 'NRSNG_SRVC_ONST_NRSDNT_SW', 'NRSNG_2_SRVC_CD', 'NRSNG_3_SRVC_CD', 'NRSNG_SRVC_OFSITE_RSDNT_SW', 'NRSNG_SRVC_ONST_RSDNT_SW', 'NTRTNL_GDNC_SRVC_CD', 'OT_SRVC_ONST_NRSDNT_SW', 'OT_2_SRVC_CD', 'OT_3_SRVC_CD', 'OT_SRVC_OFSITE_RSDNT_SW', 'OT_SRVC_ONST_RSDNT_SW', 'ORTHTC_PRSTHTC_2_SRVC_CD', 'ORTHTC_PRSTHTC_3_SRVC_CD', 'OTHR_SRVC_CD', 'ACTVTY_OTHR_OFSITE_RSDNT_SW', 'ACTVTY_OTHR_ONST_NRSDNT_SW', 'ACTVTY_OTHR_ONST_RSDNT_SW', 'SCL_SRVC_OTHR_OFSITE_RSDNT_SW', 'SCL_SRVC_OTHR_ONST_NRSDNT_SW', 'SCL_SRVC_OTHR_ONST_RSDNT_SW', 'PHRMCY_SRVC_OFSITE_RSDNT_SW', 'PHRMCY_SRVC_ONST_NRSDNT_SW', 'PHRMCY_SRVC_ONST_RSDNT_SW', 'PT_2_SRVC_CD', 'PT_3_SRVC_CD', 'PT_OFSITE_RSDNT_SW', 'PT_ONST_NRSDNT_SW', 'PT_ONST_RSDNT_SW', 'PHYSN_SRVC_CD', 'PHYSN_2_SRVC_CD', 'PHYSN_3_SRVC_CD', 'PHYSN_SRVC_OFSITE_RSDNT_SW', 'PHYSN_SRVC_ONST_NRSDNT_SW', 'PHYSN_SRVC_ONST_RSDNT_SW', 'PDTRY_SRVC_OFSITE_RSDNT_SW', 'PDTRY_SRVC_ONST_NRSDNT_SW', 'PDTRY_SRVC_ONST_RSDNT_SW', 'PSYCHLGCL_SRVC_CD', 'PSYCHLGCL_2_SRVC_CD', 'PSYCHLGCL_3_SRVC_CD', 'RDLGY_SRVC_CD', 'RSPRTRY_CARE_2_SRVC_CD', 'RSPRTRY_CARE_3_SRVC_CD', 'SHRT_TERM_IP_SRVC_CD', 'SCL_2_SRVC_CD', 'SCL_3_SRVC_CD', 'SCL_WORK_SRVC_OFSITE_RSDNT_SW', 'SCL_WORK_SRVC_ONST_NRSDNT_SW', 'SCL_WORK_SRVC_ONST_RSDNT_SW', 'SPCH_PTHLGY_2_SRVC_CD', 'SPCH_PTHLGY_3_SRVC_CD', 'SPCH_PTHLGY_OFSITE_RSDNT_SW', 'SPCH_PTHLGY_ONST_NRSDNT_SW', 'SPCH_PTHLGY_ONST_RSDNT_SW', 'SPCH_THRPY_SRVC_CD', 'THRPTC_RCRTNL_OFSITE_RSDNT_SW', 'THRPTC_RCRTNL_ONST_NRSDNT_SW', 'THRPTC_RCRTNL_ONST_RSDNT_SW', 'VCTNL_GDNC_SRVC_CD', 'VCTNL_SRVC_OFSITE_RSDNT_SW', 'VCTNL_SRVC_ONST_NRSDNT_SW', 'VCTNL_SRVC_ONST_RSDNT_SW', 'DGNSTC_XRAY_OFSITE_RSDNT_SW', 'DGNSTC_XRAY_ONST_NRSDNT_SW', 'DGNSTC_XRAY_ONST_RSDNT_SW', 'OPEN_HRT_SRGRY_SRVC_CD', 'PSTOPRTV_RCVRY_SRVC_CD', 'ACUTE_RNL_DLYS_SRVC_CD', 'ACUTE_RNL_DLYS_SRVC_DESC', 'ALCHL_DRUG_SRVC_DESC', 'ALCHL_DRUG_SRVC_CD', 'ANSTHSA_SRVC_CD', 'ANSTHSA_SRVC_DESC', 'AUDLGY_SRVC_CD', 'AUDLGY_SRVC_DESC', 'BURN_CARE_UNIT_SRVC_CD', 'BURN_CARE_UNIT_SRVC_DESC', 'OPEN_HRT_SRGRY_SRVC_DESC', 'CRDC_CTHTRZTN_LAB_SRVC_CD', 'CRDC_CTHTRZTN_LAB_SRVC_DESC', 'CARF_IP_REHAB_SRVC_CD', 'CARF_IP_REHAB_SRVC_DESC', 'CHMTHRPY_SRVC_CD', 'CHMTHRPY_SRVC_DESC', 'CHLD_ADLSCNT_PSYCH_SRVC_DESC', 'CHRPRCTIC_SRVC_CD', 'CHRPRCTIC_SRVC_DESC', 'CL_SRVC_CD', 'CL_SRVC_DESC', 'CT_SCAN_SRVC_CD', 'CT_SCAN_SRVC_DESC', 'DNTL_SRVC_CD', 'DNTL_SRVC_DESC', 'DGNSTC_RDLGY_SRVC_DESC', 'DTRY_SRVC_CD', 'DTRY_SRVC_DESC', 'DCTD_ER_SRVC_DESC', 'DCTD_ER_SRVC_CD', 'XTRCRPRL_SHCK_LTHTRPTR_SRVC_CD', 'XTRCRPRL_SHCK_LTHTRPTR_SRVCDSC', 'GRNTLGCL_SPCLTY_SRVC_CD', 'GRNTLGCL_SPCLTY_SRVC_DESC', 'CRNRY_CARE_UNIT_SRVC_CD', 'CRNRY_CARE_UNIT_SRVC_DESC', 'ICU_SRVC_CD', 'ICU_SRVC_DESC', 'NEONTL_ICU_SRVC_CD', 'PED_ICU_SRVC_CD', 'SRGCL_ICU_SRVC_CD', 'IP_SRGCL_SRVC_CD', 'IP_SRGCL_SRVC_DESC', 'MGNTC_RSNC_IMG_SRVC_CD', 'MGNTC_RSNC_IMG_SRVC_DESC', 'NEONTL_ICU_SRVC_DESC', 'NEONTL_NRSRY_SRVC_CD', 'NEONTL_NRSRY_SRVC_DESC', 'NRSRGCL_SRVC_DESC', 'NRSRGCL_SRVC_CD', 'NUCLR_MDCN_SRVC_CD', 'NUCLR_MDCN_SRVC_DESC', 'OB_SRVC_CD', 'OB_SRVC_DESC', 'OT_SRVC_CD', 'OT_SRVC_DESC', 'OPRTG_ROOM_SRVC_DESC', 'OPRTG_ROOM_SRVC_CD', 'OPTHLMC_SRGY_SRVC_CD', 'OPTHLMC_SRGY_SRVC_DESC', 'OPTMTRC_SRVC_CD', 'OPTMTRC_SRVC_DESC', 'ORGN_TRNSPLNT_SRVC_CD', 'ORGN_TRNSPLNT_SRVC_DESC', 'ORTHPDC_SRGY_SRVC_CD', 'ORTHPDC_SRGY_SRVC_DESC', 'OP_SRVC_CD', 'OP_SRVC_DESC', 'OP_SRGRY_UNIT_SRVC_CD', 'OP_SRGRY_UNIT_SRVC_DESC', 'PED_SRVC_CD', 'PED_SRVC_DESC', 'PED_ICU_SRVC_DESC', 'PET_SCAN_SRVC_CD', 'PET_SCAN_SRVC_DESC', 'PHRMCY_SRVC_CD', 'PHRMCY_SRVC_DESC', 'PT_SRVC_CD', 'PT_SRVC_DESC', 'PSTOPRTV_RCVRY_SRVC_DESC', 'PSYCH_SRVC_CD', 'PSYCH_SRVC_DESC', 'EMER_PSYCH_SRVC_CD', 'FRNSC_PSYCH_SRVC_CD', 'GRTRC_PSYCH_SRVC_CD', 'OP_PSYCH_SRVC_CD', 'CHLD_ADLSCNT_PSYCH_SRVC_CD', 'EMER_PSYCH_SRVC_DESC', 'FRNSC_PSYCH_SRVC_DESC', 'GRTRC_PSYCH_SRVC_DESC', 'OP_PSYCH_SRVC_DESC', 'DGNSTC_RDLGY_SRVC_CD', 'THRPTC_RDLGY_SRVC_CD', 'THRPTC_RDLGY_SRVC_DESC', 'RCNSTRCTN_SRGY_SRVC_DESC', 'RCNSTRCTN_SRGY_SRVC_CD', 'OP_REHAB_SRVC_CD', 'OP_REHAB_SRVC_DESC', 'RSPRTRY_CARE_SRVC_CD', 'RSPRTRY_CARE_SRVC_DESC', 'SCL_SRVC_CD', 'SCL_SRVC_DESC', 'SPCH_PTHLGY_SRVC_CD', 'SPCH_PTHLGY_SRVC_DESC', 'SRGCL_ICU_SRVC_DESC', 'MDCR_TRNSPLNT_CNTR_SRVC_CD', 'MDCR_TRNSPLNT_CNTR_SRVC_DESC', 'SHCK_TRMA_SRVC_CD', 'SHCK_TRMA_SRVC_DESC', 'URGNT_CARE_SRVC_CD', 'URGNT_CARE_SRVC_DESC', 'SCL_WORKR_CNTRCT_CNT', 'SCL_WORKR_FLTM_CNT', 'SCL_WORKR_PRTM_CNT', 'SCL_WORKR_CNT', 'REHAB_BED_CNT', 'AIDS_BED_CNT', 'ALZHMR_BED_CNT', 'DLYS_BED_CNT', 'DSBL_CHLDRN_BED_CNT', 'HEAD_TRMA_BED_CNT', 'HOSPC_BED_CNT', 'HNTGTN_DEASE_BED_CNT', 'VNTLTR_BED_CNT', 'THORC_SRGRY_SW', 'URLGY_SRGRY_SW', 'CRDVSCLR_SRGRY_SW', 'FT_SRGRY_SW', 'NRLGCL_SRGRY_SW', 'OB_GYN_SRGRY_SW', 'OPTHMLGY_SRGRY_SW', 'ORAL_SRGRY_SW', 'ORTHPDC_SRGRY_SW', 'OTLRYNGLGY_SRGRY_SW', 'PLSTC_SRGRY_SW', 'GNRL_SRGRY_SW', 'SPCH_PTHLGST_CNTRCT_CNT', 'SPCH_PTHLGST_FLTM_CNT', 'SPCH_PTHLGST_PRTM_CNT', 'SPCH_PTHLGST_AUDLGST_CNT', 'SPCH_PTHLGST_ARNGMT_CNT', 'SPCH_PTHLGST_CNT', 'HMDLYS_STN_ESRD_CNT', 'DLYS_STN_CNT', 'SBUNIT_OPRTN_SW', 'SBUNIT_SW', 'SBUNIT_CNT', 'SRTY_BOND_CD', 'SB_SIZE_CD', 'SB_SW', 'TCHNLGST_2_YR_RDLGC_CNT', 'TCHNLGST_ASCT_DGR_CNT', 'TCHNLGST_BS_BA_DGR_CNT', 'THRPTC_RCRTNL_CNTRCT_CNT', 'THRPTC_RCRTNL_FLTM_CNT', 'THRPTC_RCRTNL_PRTM_CNT', 'FED_PGM_NAME', 'EMPLEE_CNT', 'GNRL_FAC_TYPE_CD', 'NPP_TYPE_CD', 'VLNTR_OTHR_CNT', 'VLNTR_CNT', 'cross_rfrnc_prvdr_num', 'rltd_prvdr_num', 'PSYCH_UNIT_TRMNN_DT']